/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
 */
export type DeviceID = string;
/**
 * What happened on the input.
 */
export type InputAction = "press" | "release" | "rotate_cw" | "rotate_ccw" | "click";
/**
 * RGB color as a '#RRGGBB' hex string. Accepted in any case; the daemon stores and returns it lowercase, so clients can compare colors as strings. '#000000' turns the LED off. Hardware-agnostic: the daemon translates it to whatever the device understands (e.g. switching the device to a per-key lighting mode first).
 */
export type Color = string;

/**
 * Creates a new profile. The server generates the id and returns the profile with an empty bindings array.
 */
export interface MethodCreateProfile {
  params: {
    /**
     * Human-friendly name for the new profile.
     */
    name: string;
  };
  result: {
    profile: Profile;
  };
}
/**
 * A named set of bindings. The daemon keeps exactly one profile active at a time; switching profiles swaps the active binding set.
 */
export interface Profile {
  /**
   * Stable server-generated identifier for the profile.
   */
  id: string;
  /**
   * Human-friendly profile name.
   */
  name: string;
  /**
   * Bindings that belong to this profile.
   */
  bindings: Binding[];
  /**
   * LED colors this profile paints on RGB-capable inputs, applied by the daemon whenever the profile becomes active. An RGB input with no entry here is turned off. At most one entry per (device_id, input_id); the daemon enforces uniqueness. Absent means no colors.
   */
  colors?: InputColor[];
}
/**
 * Maps an input on a specific device to an action.
 */
export interface Binding {
  device_id: DeviceID;
  input_id: string;
  trigger: InputAction;
  action: Action;
}
/**
 * An executable action bound to an input.
 */
export interface Action {
  /**
   * Action type. Built-ins are well-known; plugin actions use 'plugin.<plugin_id>.<action_id>'. Plugin ids are reverse-DNS (they contain dots) and action ids never do, so the action id is everything after the last dot.
   */
  type: string;
  /**
   * Action-specific parameters. Schema depends on 'type'. The daemon validates them against the per-type ActionParams definition (e.g. DelayActionParams for type 'delay').
   */
  params?: {
    [k: string]: unknown;
  };
}
/**
 * LED color assigned to one input of a device.
 */
export interface InputColor {
  device_id: DeviceID;
  /**
   * Logical identifier of the input within the device. Matches Device.inputs[].id.
   */
  input_id: string;
  color: Color;
}
