/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Deletes a profile. The daemon never deletes the last remaining profile. Deleting the active profile reassigns the active one, so the resulting active profile id is always returned.
 */
export interface MethodDeleteProfile {
  params: {
    /**
     * Identifier of the profile to delete.
     */
    id: string;
  };
  result: {
    /**
     * Identifier of the profile that is active after the deletion. Unchanged unless the deleted profile was the active one.
     */
    active_profile_id: string;
  };
}
