/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Serializes the profile identified by 'id' as a portable ExportedProfile document and writes it to 'path' on the daemon host's filesystem. The exported file omits the server-local id. Returns the path that was written.
 */
export interface MethodExportProfile {
  params: {
    /**
     * Identifier of the profile to export.
     */
    id: string;
    /**
     * Filesystem path on the daemon host where the exported file is written.
     */
    path: string;
  };
  result: {
    /**
     * Echo of the path that was written.
     */
    path: string;
  };
}
