/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Returns the current auto-switch configuration: the master toggle and the full set of app-to-profile rules. The daemon uses these to switch the active profile based on the foreground application.
 */
export interface MethodGetAutoSwitch {
  /**
   * No parameters in v1.
   */
  params: {};
  result: {
    /**
     * Master toggle. When false, the daemon ignores the rules and never auto-switches.
     */
    enabled: boolean;
    /**
     * App-to-profile rules currently configured.
     */
    rules: AutoSwitchRule[];
  };
}
/**
 * Maps a foreground application to the profile that should become active while that app is frontmost. When the frontmost app matches no rule, the active profile is left unchanged (sticky behavior); there is no fallback profile.
 */
export interface AutoSwitchRule {
  /**
   * OS-native application identifier: bundle id on macOS, executable name on Linux/Windows. Opaque string, not portable across OSes; the daemon matches it verbatim against the frontmost app.
   */
  app: string;
  /**
   * Identifier of the profile to activate when this app is frontmost.
   */
  profile_id: string;
}
