/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Mandatory first request after a WebSocket connection is established. The client declares the protocol_version it speaks. The server either accepts (Response.ok=true with its own identification) or closes the connection with an UNSUPPORTED_PROTOCOL_VERSION error. After a successful hello no further version negotiation happens; the contract is fixed for the session.
 */
export interface MethodHello {
  params: {
    /**
     * Major version of the protocol the client implements. Currently '1'.
     */
    protocol_version: "1";
    client: PeerInfo;
  };
  result: {
    /**
     * Protocol version the server agrees to speak for this session.
     */
    protocol_version: "1";
    server: PeerInfo;
  };
}
/**
 * Self-identification of a protocol peer (client or server).
 *
 * This interface was referenced by `MethodHello`'s JSON-Schema
 * via the `definition` "PeerInfo".
 */
export interface PeerInfo {
  /**
   * Stable identifier of the peer implementation.
   */
  name: string;
  /**
   * Semver version of the peer build.
   */
  version: string;
}
