/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
 */
export type DeviceID = string;
/**
 * Kind of physical input.
 */
export type InputKind = "key" | "encoder";
/**
 * Color the active profile paints on this input. Only set on RGB inputs that have a color in the active profile; absent means the LED is off.
 */
export type Color = string;
/**
 * Clockwise rotation, in degrees, applied to the canonical orientation of a device's layout so clients show it the way the user has the device on the desk. Presentation only: bindings and colors stay tied to the physical input (input_id) and do not change when the device is rotated. It is a per-device preference, not a per-profile one: switching profiles does not change it. Set through set_device_rotation and exposed in Device.rotation, where absent means 0.
 */
export type DeviceRotation = 0 | 90 | 180 | 270;

/**
 * Returns the HID devices currently known to the daemon. No filters in v1; clients filter client-side if needed.
 */
export interface MethodListDevices {
  /**
   * No parameters in v1.
   */
  params: {};
  result: {
    /**
     * All currently enumerated HID devices.
     */
    devices: Device[];
  };
}
/**
 * A HID device known to the daemon. Returned by list_devices.
 */
export interface Device {
  id: DeviceID;
  /**
   * USB Vendor ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
   */
  vendor_id: string;
  /**
   * USB Product ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
   */
  product_id: string;
  /**
   * Manufacturer string from the HID descriptor. May be missing on cheap/clone devices.
   */
  manufacturer?: string;
  /**
   * Product name string from the HID descriptor.
   */
  product?: string;
  /**
   * Serial number string from the HID descriptor. Not all HID devices expose one.
   */
  serial_number?: string;
  /**
   * OS-opaque path used by the HID library to (re)open the device. Format varies per OS; clients should treat it as an opaque token.
   */
  path: string;
  /**
   * Inputs (keys/encoders) the daemon knows this device exposes. Empty for unrecognized devices the daemon can't map.
   */
  inputs: Input[];
  rotation?: DeviceRotation;
}
/**
 * A single physical input exposed by a device (a key or an encoder).
 */
export interface Input {
  /**
   * Logical identifier of the input within the device (e.g. 'key_0x04', 'encoder_0'). Matches InputEvent.input_id and Binding.input_id.
   */
  id: string;
  kind: InputKind;
  /**
   * Fixed name of the input (e.g. 'Enter', 'Play') that clients show as-is in any orientation. When absent, clients name the input by position: they number inputs per kind in reading order of the current view, sorting by each input's top-left corner after applying Device.rotation (y first, then x), so 'Key 1' is always the top-left key as the device sits on the desk. If the device has no complete layout, they number inputs per kind in the order list_devices returns them. Catalogs should not send positional labels like 'Key 1': they would be wrong once the device is rotated.
   */
  label?: string;
  layout?: InputLayout;
  /**
   * Whether the input has an RGB LED the daemon can drive through set_input_color. Absent means false.
   */
  rgb?: boolean;
  color?: Color;
}
/**
 * Physical position and size of an input, in key units (1 = one standard key). Fractions are allowed (e.g. x: 5.5 leaves a gap before a column of encoders). Coordinates are in the device's canonical orientation, defined by the daemon's device catalog: the origin is the top-left corner and y grows downwards. This is a coordinate system, not how the user has the device on the desk (that is Device.rotation). The shape is not modeled: clients derive it from Input.kind (key = rectangle, encoder = circle). Clients can draw a device only when every one of its inputs has a layout; otherwise they fall back to a view without positions (e.g. a list). Prior art: the {x, y, w, h} key model of QMK/VIA info.json.
 */
export interface InputLayout {
  /**
   * Horizontal position of the input's top-left corner, in key units.
   */
  x: number;
  /**
   * Vertical position of the input's top-left corner, in key units. Grows downwards.
   */
  y: number;
  /**
   * Width in key units. Absent means 1.
   */
  w?: number;
  /**
   * Height in key units. Absent means 1.
   */
  h?: number;
}
