/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
 */
export type DeviceID = string;

/**
 * Returns the HID devices currently known to the daemon. No filters in v1; clients filter client-side if needed.
 */
export interface MethodListDevices {
  /**
   * No parameters in v1.
   */
  params: {};
  result: {
    /**
     * All currently enumerated HID devices.
     */
    devices: Device[];
  };
}
/**
 * A HID device known to the daemon. Returned by list_devices.
 */
export interface Device {
  id: DeviceID;
  /**
   * USB Vendor ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
   */
  vendor_id: string;
  /**
   * USB Product ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
   */
  product_id: string;
  /**
   * Manufacturer string from the HID descriptor. May be missing on cheap/clone devices.
   */
  manufacturer?: string;
  /**
   * Product name string from the HID descriptor.
   */
  product?: string;
  /**
   * Serial number string from the HID descriptor. Not all HID devices expose one.
   */
  serial_number?: string;
  /**
   * OS-opaque path used by the HID library to (re)open the device. Format varies per OS; clients should treat it as an opaque token.
   */
  path: string;
}
