/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
 */
export type DeviceID = string;
/**
 * Kind of physical input.
 */
export type InputKind = "key" | "encoder";

/**
 * Returns the HID devices currently known to the daemon. No filters in v1; clients filter client-side if needed.
 */
export interface MethodListDevices {
  /**
   * No parameters in v1.
   */
  params: {};
  result: {
    /**
     * All currently enumerated HID devices.
     */
    devices: Device[];
  };
}
/**
 * A HID device known to the daemon. Returned by list_devices.
 */
export interface Device {
  id: DeviceID;
  /**
   * USB Vendor ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
   */
  vendor_id: string;
  /**
   * USB Product ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
   */
  product_id: string;
  /**
   * Manufacturer string from the HID descriptor. May be missing on cheap/clone devices.
   */
  manufacturer?: string;
  /**
   * Product name string from the HID descriptor.
   */
  product?: string;
  /**
   * Serial number string from the HID descriptor. Not all HID devices expose one.
   */
  serial_number?: string;
  /**
   * OS-opaque path used by the HID library to (re)open the device. Format varies per OS; clients should treat it as an opaque token.
   */
  path: string;
  /**
   * Inputs (keys/encoders) the daemon knows this device exposes. Empty for unrecognized devices the daemon can't map.
   */
  inputs: Input[];
}
/**
 * A single physical input exposed by a device (a key or an encoder).
 */
export interface Input {
  /**
   * Logical identifier of the input within the device (e.g. 'key_0x04', 'encoder_0'). Matches InputEvent.input_id and Binding.input_id.
   */
  id: string;
  kind: InputKind;
  /**
   * Human-friendly label for the input (e.g. 'Key 1', 'Encoder'). Optional; clients fall back to id.
   */
  label?: string;
}
