/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
 */
export type DeviceID = string;
/**
 * What happened on the input.
 */
export type InputAction = "press" | "release" | "rotate_cw" | "rotate_ccw" | "click";

/**
 * Returns all profiles the daemon currently has, along with the id of the active one. The active profile id is tracked at the daemon level and only exposed here.
 */
export interface MethodListProfiles {
  /**
   * No parameters in v1.
   */
  params: {};
  result: {
    /**
     * All profiles known to the daemon.
     */
    profiles: Profile[];
    /**
     * Identifier of the currently active profile. Always references one of the profiles in the array.
     */
    active_profile_id: string;
  };
}
/**
 * A named set of bindings. The daemon keeps exactly one profile active at a time; switching profiles swaps the active binding set.
 */
export interface Profile {
  /**
   * Stable server-generated identifier for the profile.
   */
  id: string;
  /**
   * Human-friendly profile name.
   */
  name: string;
  /**
   * Bindings that belong to this profile.
   */
  bindings: Binding[];
}
/**
 * Maps an input on a specific device to an action.
 */
export interface Binding {
  device_id: DeviceID;
  input_id: string;
  trigger: InputAction;
  action: Action;
}
/**
 * An executable action bound to an input.
 */
export interface Action {
  /**
   * Action type. Built-ins are well-known; plugin actions use 'plugin.<plugin_id>.<action_id>'.
   */
  type: string;
  /**
   * Action-specific parameters. Schema depends on 'type'.
   */
  params?: {
    [k: string]: unknown;
  };
}
