/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Globally unique reverse-DNS plugin id; install folder name and <plugin_id> in Action.type.
 */
export type PluginID = string;
/**
 * Kind of physical input.
 */
export type InputKind = "key" | "encoder";

/**
 * Returns every installed plugin with the state of its process. No params in v1.
 */
export interface MethodListPlugins {
  /**
   * No parameters in v1.
   */
  params: {};
  result: {
    /**
     * Installed plugins.
     */
    plugins: InstalledPlugin[];
  };
}
/**
 * A plugin installed in the daemon, with the state of its process.
 */
export interface InstalledPlugin {
  manifest: PluginManifest;
  /**
   * State of the plugin process: 'starting' (spawned, hello not received yet), 'running' (connected), 'stopped' (not running, e.g. exited cleanly) or 'error' (failed to start or crashed; see 'error').
   */
  status: "starting" | "running" | "stopped" | "error";
  /**
   * Human-readable reason why the plugin failed. The daemon sets it only when status is 'error' (not enforced by the schema).
   */
  error?: string;
}
/**
 * Contents of the manifest.json file at the root of a plugin. A plugin is distributed as a '.keyforgeplugin' file: a zip archive with manifest.json at its root (no wrapping folder) plus every file the manifest references. The daemon installs it by extracting the archive into '<config dir>/plugins/<id>/', taking the id from the manifest. All file paths in the manifest (icon, and entrypoint paths containing '/') are relative to the plugin root, use '/' as separator, and must stay inside the plugin root: the daemon rejects '..' segments and any path or archive entry that escapes the root.
 */
export interface PluginManifest {
  /**
   * Manifest format version. Currently 1; bumped if the manifest shape changes.
   */
  manifest_version: 1;
  id: PluginID;
  /**
   * Human-friendly plugin name for the UI.
   */
  name: string;
  /**
   * Plugin version (SemVer 2.0).
   */
  version: string;
  /**
   * Major version of the protocol the plugin speaks. Lets the daemon reject an incompatible plugin before spawning it. Currently '1'.
   */
  protocol_version: "1";
  /**
   * Plugin author, shown in the UI.
   */
  author?: string;
  /**
   * Short description of what the plugin does.
   */
  description?: string;
  /**
   * URL of the plugin homepage or source repository.
   */
  homepage?: string;
  /**
   * Category the UI groups the plugin's actions under (e.g. 'Audio', 'Streaming').
   */
  category?: string;
  /**
   * Path to the plugin icon, relative to the plugin root. No leading '/', no '\' and no ':'.
   */
  icon?: string;
  /**
   * Command the daemon runs to start the plugin, per OS (keys match Go's GOOS). The plugin supports exactly the OSes listed here.
   */
  entrypoint: {
    darwin?: PluginCommand;
    linux?: PluginCommand;
    windows?: PluginCommand;
  };
  /**
   * Actions the plugin exposes. Each becomes bindable as 'plugin.<id>.<action id>'.
   *
   * @minItems 1
   */
  actions: [PluginAction, ...PluginAction[]];
}
/**
 * Executable plus arguments used to start a plugin process.
 */
export interface PluginCommand {
  /**
   * Executable to run. A path containing '/' is resolved relative to the plugin root; a bare name (e.g. 'node') is looked up on the PATH. Always use '/' as separator, also on Windows; absolute paths, '\' and ':' are not allowed.
   */
  path: string;
  /**
   * Arguments passed to the executable.
   */
  args?: string[];
}
/**
 * An action a plugin exposes, declared in its manifest.
 */
export interface PluginAction {
  /**
   * Action identifier, unique within the plugin. snake_case, no dots.
   */
  id: string;
  /**
   * Human-friendly action name for the UI.
   */
  name: string;
  /**
   * Optional longer description of what the action does.
   */
  description?: string;
  /**
   * Input kinds the action can be bound to. Omitted means any kind.
   *
   * @minItems 1
   */
  inputs?: [InputKind, ...InputKind[]];
  /**
   * Params this action accepts, in display order.
   */
  params: ParamSpec[];
}
/**
 * Describes one action parameter so a client can render an input for it.
 */
export interface ParamSpec {
  /**
   * Param key written into Action.params. Unique within the action.
   */
  name: string;
  /**
   * Human-friendly field label.
   */
  label: string;
  /**
   * Param value type, which sets the JSON type written into Action.params: 'string' a string, 'boolean' a boolean, 'color' a Color ('#RRGGBB' string, rendered as a color picker), 'input' a string holding the Input.id of an input on the same device as the binding that fires the action. An optional boolean that is absent means false. placeholder only applies to 'string' and 'input'. 'input' is rendered as a picker listing that device's inputs (narrowed by input_filter), named and ordered as in the visual editor: Input.label, or numbered per kind in reading order of the rotated view. An optional 'input' that is absent means nothing was picked; each action defines what that means (for set_color, the input that fired the action). The stored value is always the Input.id (the physical input), never a position or a numbered label: Device.rotation is presentation only, so rotating the device after saving does not change which physical input the param targets, while the label the picker shows for it does change (at 180 degrees the top-left key becomes the bottom-right one). Clients translate both ways with the current rotation: label to id when picking, id to label when showing a saved value. Whether the id exists on the device is checked when the action runs, not when the binding is saved (the device may be disconnected).
   */
  type: "string" | "boolean" | "color" | "input";
  required: boolean;
  /**
   * For 'string': placeholder/example shown in the text field. For 'input': label of the picker's 'nothing picked' option in an optional param, describing what the action does when no input is picked (e.g. set_color: 'This key (the one that fired)'); a required 'input' param has no such option, so clients ignore it. Does not apply to 'boolean' or 'color'.
   */
  placeholder?: string;
  input_filter?: InputFilter;
}
/**
 * Narrows which inputs a ParamSpec of type 'input' lets the user pick. Only valid with type 'input': a ParamSpec of any other type that carries it is rejected. Absent means any input of the device.
 */
export interface InputFilter {
  /**
   * Only inputs of these kinds. Absent means any kind.
   *
   * @minItems 1
   */
  kinds?: [InputKind, ...InputKind[]];
  /**
   * true: only inputs with an LED (Input.rgb). false or absent: no filtering by LED.
   */
  rgb?: boolean;
}
