/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Returns the catalog of actions the daemon can bind to inputs, including the param shape each action needs so a client can render a config form. No params in v1.
 */
export interface MethodListActions {
  /**
   * No parameters in v1.
   */
  params: {};
  result: {
    /**
     * All actions available to bind. Built-ins plus any registered plugin actions.
     */
    actions: ActionDescriptor[];
  };
}
/**
 * Describes a bindable action type and the params it accepts.
 *
 * This interface was referenced by `MethodListActions`'s JSON-Schema
 * via the `definition` "ActionDescriptor".
 */
export interface ActionDescriptor {
  /**
   * Action type, as used in Action.type (e.g. 'launch_app').
   */
  type: string;
  /**
   * Human-friendly action name for the UI.
   */
  name: string;
  /**
   * Optional longer description of what the action does.
   */
  description?: string;
  /**
   * Params this action accepts, in display order.
   */
  params: ParamSpec[];
}
/**
 * Describes one action parameter so a client can render an input for it.
 *
 * This interface was referenced by `MethodListActions`'s JSON-Schema
 * via the `definition` "ParamSpec".
 */
export interface ParamSpec {
  /**
   * Param key written into Action.params.
   */
  name: string;
  /**
   * Human-friendly field label.
   */
  label: string;
  /**
   * Param value type. Only 'string' in v1.
   */
  type: "string";
  required: boolean;
  /**
   * Optional placeholder/example shown in the input.
   */
  placeholder?: string;
}
