/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Renames an existing profile. Does not affect its bindings or the active profile.
 */
export interface MethodRenameProfile {
  params: {
    /**
     * Identifier of the profile to rename.
     */
    id: string;
    /**
     * New human-friendly name for the profile.
     */
    name: string;
  };
  /**
   * Empty acknowledgement object. Reserved for future fields without breaking the schema.
   */
  result: {};
}
