/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Sets which profile is active. The active profile is the one the binding editor reads and writes; switching it swaps the live binding set.
 */
export interface MethodSetActiveProfile {
  params: {
    /**
     * Identifier of the profile to activate.
     */
    id: string;
  };
  result: {
    /**
     * Identifier of the now-active profile. Echoes the requested id on success.
     */
    active_profile_id: string;
  };
}
