/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Replaces the entire auto-switch configuration in one shot (bulk set, not per-rule CRUD): the master toggle and the full rule set. The result echoes the persisted state. The daemon rejects the whole request with error code PROFILE_NOT_FOUND if any rule's profile_id does not exist; nothing is persisted in that case.
 */
export interface MethodSetAutoSwitch {
  params: {
    /**
     * Master toggle. When false, the daemon ignores the rules and never auto-switches.
     */
    enabled: boolean;
    /**
     * Full replacement set of app-to-profile rules. Any previously stored rules are discarded.
     */
    rules: AutoSwitchRule[];
  };
  result: {
    /**
     * Master toggle as persisted. Echoes the requested value on success.
     */
    enabled: boolean;
    /**
     * Rules as persisted. Echoes the requested set on success.
     */
    rules: AutoSwitchRule[];
  };
}
/**
 * Maps a foreground application to the profile that should become active while that app is frontmost. When the frontmost app matches no rule, the active profile is left unchanged (sticky behavior); there is no fallback profile.
 */
export interface AutoSwitchRule {
  /**
   * OS-native application identifier: bundle id on macOS, executable name on Linux/Windows. Opaque string, not portable across OSes; the daemon matches it verbatim against the frontmost app.
   */
  app: string;
  /**
   * Identifier of the profile to activate when this app is frontmost. Must reference an existing profile: set_auto_switch rejects unknown ids with PROFILE_NOT_FOUND, and delete_profile removes the rules pointing to the deleted profile.
   */
  profile_id: string;
}
