/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Id of the plugin to uninstall.
 */
export type PluginID = string;

/**
 * Stops the plugin's process and deletes its folder. Bindings that use the plugin's actions are left untouched (orphaned): while the plugin is missing, firing them does nothing, and reinstalling the plugin makes them work again.
 */
export interface MethodUninstallPlugin {
  params: {
    id: PluginID;
  };
  /**
   * Empty acknowledgement object. Reserved for future fields without breaking the schema.
   */
  result: {};
}
