.PHONY: help generate generate-go generate-ts generate-ts-barrel build-ts validate validate-frames validate-methods validate-events clean check-tools

SCHEMAS_DIR := schemas
EXAMPLES_DIR := examples
GO_OUT      := go/protocol
TS_OUT      := ts/src
TS_METHODS_OUT := $(TS_OUT)/methods
TS_EVENTS_OUT  := $(TS_OUT)/events

# Go-installed binaries (go-jsonschema) live in $GOPATH/bin which is not always
# on the user's PATH. Prepend it so make recipes always find them.
GOBIN := $(shell go env GOPATH)/bin
export PATH := $(GOBIN):$(PATH)

# All schema files, used as deps for generation.
COMMON_SCHEMA   := $(SCHEMAS_DIR)/common.schema.json
ENVELOPE_SCHEMA := $(SCHEMAS_DIR)/envelope.schema.json
METHOD_SCHEMAS  := $(wildcard $(SCHEMAS_DIR)/methods/*.schema.json)
EVENT_SCHEMAS   := $(wildcard $(SCHEMAS_DIR)/events/*.schema.json)
ALL_SCHEMAS     := $(COMMON_SCHEMA) $(ENVELOPE_SCHEMA) $(METHOD_SCHEMAS) $(EVENT_SCHEMAS)

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-20s %s\n", $$1, $$2}'

check-tools: ## Verify required generators are installed
	@command -v go-jsonschema >/dev/null 2>&1 || { echo "ERROR: go-jsonschema not found. Run: go install github.com/atombender/go-jsonschema@latest"; exit 1; }
	@command -v json2ts >/dev/null 2>&1 || { echo "ERROR: json-schema-to-typescript not found. Run: npm install -g json-schema-to-typescript"; exit 1; }
	@command -v ajv >/dev/null 2>&1 || { echo "ERROR: ajv-cli not found. Run: npm install -g ajv-cli"; exit 1; }

generate: check-tools generate-go generate-ts ## Generate Go and TS types from schemas

generate-go: ## Generate Go types into the go/ submodule
	@mkdir -p $(GO_OUT)
	$(GOBIN)/go-jsonschema -p protocol -o $(GO_OUT)/types.go $(ALL_SCHEMAS)
	@echo "✓ Generated Go types in $(GO_OUT)/"

generate-ts: ## Generate TypeScript types into the ts/ package
	@rm -rf $(TS_OUT)
	@mkdir -p $(TS_METHODS_OUT) $(TS_EVENTS_OUT)
	@json2ts -i $(COMMON_SCHEMA) -o $(TS_OUT)/common.ts --cwd=$(SCHEMAS_DIR) --unreachableDefinitions >/dev/null
	@json2ts -i $(ENVELOPE_SCHEMA) -o $(TS_OUT)/envelope.ts --cwd=$(SCHEMAS_DIR) --unreachableDefinitions >/dev/null
	@for schema in $(METHOD_SCHEMAS); do \
		base=$$(basename $$schema .schema.json); \
		json2ts -i $$schema -o $(TS_METHODS_OUT)/$$base.ts --cwd=$(SCHEMAS_DIR)/methods --unreachableDefinitions >/dev/null; \
	done
	@for schema in $(EVENT_SCHEMAS); do \
		base=$$(basename $$schema .schema.json); \
		json2ts -i $$schema -o $(TS_EVENTS_OUT)/$$base.ts --cwd=$(SCHEMAS_DIR)/events --unreachableDefinitions >/dev/null; \
	done
	@$(MAKE) --no-print-directory generate-ts-barrel
	@echo "✓ Generated TS types in $(TS_OUT)/"

# Auto-generates ts/src/index.ts. Re-exports `common` and `envelope` in full
# (their named exports are unique) and the top-level Method*/Event* type from
# each method/event file (the rest are duplicated shared types we ignore here).
generate-ts-barrel:
	@{ \
		echo "// AUTO-GENERATED by 'make generate-ts'. DO NOT EDIT BY HAND."; \
		echo ""; \
		echo "export * from './common.js';"; \
		echo "export * from './envelope.js';"; \
		echo ""; \
		for schema in $(METHOD_SCHEMAS); do \
			base=$$(basename $$schema .schema.json); \
			pascal=$$(echo $$base | awk 'BEGIN{FS="_";OFS=""} { for(i=1;i<=NF;i++) $$i = toupper(substr($$i,1,1)) substr($$i,2) }1'); \
			echo "export type { Method$$pascal } from './methods/$$base.js';"; \
		done; \
		echo ""; \
		for schema in $(EVENT_SCHEMAS); do \
			base=$$(basename $$schema .schema.json); \
			pascal=$$(echo $$base | awk 'BEGIN{FS="_";OFS=""} { for(i=1;i<=NF;i++) $$i = toupper(substr($$i,1,1)) substr($$i,2) }1'); \
			echo "export type { Event$$pascal } from './events/$$base.js';"; \
		done; \
	} > $(TS_OUT)/index.ts

build-ts: ## Install + build the TS package (emits .d.ts and .js into ts/dist/)
	cd ts && npm install --no-audit --no-fund && npm run build

validate: check-tools validate-frames validate-methods validate-events ## Validate every example against its schema
	@echo "✓ All examples valid"

validate-frames: ## Validate envelope frames in examples/frames/
	@for ex in $(EXAMPLES_DIR)/frames/*.json; do \
		ajv validate -s $(ENVELOPE_SCHEMA) -d $$ex --spec=draft2020 -r $(COMMON_SCHEMA) || exit 1; \
	done

validate-methods: ## Validate method content examples in examples/methods/
	@for ex in $(EXAMPLES_DIR)/methods/*.json; do \
		base=$$(basename $$ex .json); \
		ajv validate -s $(SCHEMAS_DIR)/methods/$$base.schema.json -d $$ex --spec=draft2020 -r $(COMMON_SCHEMA) || exit 1; \
	done

validate-events: ## Validate event content examples in examples/events/
	@for ex in $(EXAMPLES_DIR)/events/*.json; do \
		base=$$(basename $$ex .json); \
		ajv validate -s $(SCHEMAS_DIR)/events/$$base.schema.json -d $$ex --spec=draft2020 -r $(COMMON_SCHEMA) || exit 1; \
	done

clean: ## Remove generated TS package build output
	rm -rf ts/dist
	@echo "✓ Cleaned ts/dist/"
