.PHONY: help generate generate-go generate-ts generate-ts-barrel generate-py check-py build-py build-ts validate validate-frames validate-methods validate-events validate-files clean check-tools

SCHEMAS_DIR := schemas
EXAMPLES_DIR := examples
GO_OUT      := go/protocol
TS_OUT      := ts/src
TS_METHODS_OUT := $(TS_OUT)/methods
TS_EVENTS_OUT  := $(TS_OUT)/events
PY_OUT      := py/src/keyforge_protocol

# datamodel-codegen does not run on Python 3.15 yet (it rejects its own runtime
# version), so the generator runs on 3.14 and emits 3.14 syntax. The package
# itself targets 3.15: py_postprocess.py moves TypedDict to `typing`, which has
# PEP 728 `closed=` only since 3.15.
PY_GEN_PYTHON := 3.14
PY_PYTHON     := 3.15

# Go-installed binaries (go-jsonschema) live in $GOPATH/bin which is not always
# on the user's PATH. Prepend it so make recipes always find them.
GOBIN := $(shell go env GOPATH)/bin
export PATH := $(GOBIN):$(PATH)

# All schema files, used as deps for generation.
COMMON_SCHEMA   := $(SCHEMAS_DIR)/common.schema.json
ENVELOPE_SCHEMA := $(SCHEMAS_DIR)/envelope.schema.json
METHOD_SCHEMAS  := $(wildcard $(SCHEMAS_DIR)/methods/*.schema.json)
EVENT_SCHEMAS   := $(wildcard $(SCHEMAS_DIR)/events/*.schema.json)
# Methods and events go before common on purpose: when common is processed
# first, go-jsonschema declares an integer-enum $def (e.g. DeviceRotation) a
# second time ("DeviceRotation_1") for each $ref to it from another file.
# String enums and objects are unaffected, and the output is the same otherwise.
ALL_SCHEMAS     := $(METHOD_SCHEMAS) $(EVENT_SCHEMAS) $(COMMON_SCHEMA) $(ENVELOPE_SCHEMA)

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-20s %s\n", $$1, $$2}'

check-tools: ## Verify required generators are installed
	@command -v go-jsonschema >/dev/null 2>&1 || { echo "ERROR: go-jsonschema not found. Run: go install github.com/atombender/go-jsonschema@latest"; exit 1; }
	@command -v json2ts >/dev/null 2>&1 || { echo "ERROR: json-schema-to-typescript not found. Run: npm install -g json-schema-to-typescript"; exit 1; }
	@command -v ajv >/dev/null 2>&1 || { echo "ERROR: ajv-cli not found. Run: npm install -g ajv-cli"; exit 1; }
	@command -v uv >/dev/null 2>&1 || { echo "ERROR: uv not found. See https://docs.astral.sh/uv/getting-started/installation/"; exit 1; }

generate: check-tools generate-go generate-ts generate-py ## Generate Go, TS and Python types from schemas

generate-go: ## Generate Go types into the go/ submodule
	@mkdir -p $(GO_OUT)
	$(GOBIN)/go-jsonschema -p protocol -o $(GO_OUT)/types.go $(ALL_SCHEMAS)
	@echo "✓ Generated Go types in $(GO_OUT)/"

generate-ts: ## Generate TypeScript types into the ts/ package
	@rm -rf $(TS_OUT)
	@mkdir -p $(TS_METHODS_OUT) $(TS_EVENTS_OUT)
	@json2ts -i $(COMMON_SCHEMA) -o $(TS_OUT)/common.ts --cwd=$(SCHEMAS_DIR) --unreachableDefinitions >/dev/null
	@json2ts -i $(ENVELOPE_SCHEMA) -o $(TS_OUT)/envelope.ts --cwd=$(SCHEMAS_DIR) --unreachableDefinitions >/dev/null
	@for schema in $(METHOD_SCHEMAS); do \
		base=$$(basename $$schema .schema.json); \
		json2ts -i $$schema -o $(TS_METHODS_OUT)/$$base.ts --cwd=$(SCHEMAS_DIR)/methods --unreachableDefinitions >/dev/null; \
	done
	@for schema in $(EVENT_SCHEMAS); do \
		base=$$(basename $$schema .schema.json); \
		json2ts -i $$schema -o $(TS_EVENTS_OUT)/$$base.ts --cwd=$(SCHEMAS_DIR)/events --unreachableDefinitions >/dev/null; \
	done
	@$(MAKE) --no-print-directory generate-ts-barrel
	@echo "✓ Generated TS types in $(TS_OUT)/"

# Auto-generates ts/src/index.ts. Re-exports `common` and `envelope` in full
# (their named exports are unique) and the top-level Method*/Event* type from
# each method/event file (the rest are duplicated shared types we ignore here).
generate-ts-barrel:
	@{ \
		echo "// AUTO-GENERATED by 'make generate-ts'. DO NOT EDIT BY HAND."; \
		echo ""; \
		echo "export * from './common.js';"; \
		echo "export * from './envelope.js';"; \
		echo ""; \
		for schema in $(METHOD_SCHEMAS); do \
			base=$$(basename $$schema .schema.json); \
			pascal=$$(echo $$base | awk 'BEGIN{FS="_";OFS=""} { for(i=1;i<=NF;i++) $$i = toupper(substr($$i,1,1)) substr($$i,2) }1'); \
			echo "export type { Method$$pascal } from './methods/$$base.js';"; \
		done; \
		echo ""; \
		for schema in $(EVENT_SCHEMAS); do \
			base=$$(basename $$schema .schema.json); \
			pascal=$$(echo $$base | awk 'BEGIN{FS="_";OFS=""} { for(i=1;i<=NF;i++) $$i = toupper(substr($$i,1,1)) substr($$i,2) }1'); \
			echo "export type { Event$$pascal } from './events/$$base.js';"; \
		done; \
	} > $(TS_OUT)/index.ts

generate-py: ## Generate Python types into the py/ package
	@rm -rf $(PY_OUT)
	@uvx --python $(PY_GEN_PYTHON) --from datamodel-code-generator datamodel-codegen \
		--input $(SCHEMAS_DIR) --input-file-type jsonschema --output $(PY_OUT) \
		--output-model-type typing.TypedDict --enum-field-as-literal all \
		--target-python-version $(PY_GEN_PYTHON) --formatters builtin \
		--use-schema-description --use-field-description --disable-timestamp
	@uv run --no-project --python $(PY_PYTHON) python scripts/py_postprocess.py $(PY_OUT) $(SCHEMAS_DIR)
	@echo "✓ Generated Python types in $(PY_OUT)/"

check-py: ## Type-check the Python package with mypy --strict and run its contract tests
	cd py && uvx --python $(PY_PYTHON) mypy
	cd py && PYTHONPATH=src uv run --no-project --python $(PY_PYTHON) python -m unittest discover -s tests

build-py: ## Build the Python sdist + wheel into py/dist/
	cd py && uv build

build-ts: ## Install + build the TS package (emits .d.ts and .js into ts/dist/)
	cd ts && npm install --no-audit --no-fund && npm run build

validate: check-tools validate-frames validate-methods validate-events validate-files ## Validate every example against its schema
	@echo "✓ All examples valid"

validate-frames: ## Validate envelope frames in examples/frames/
	@for ex in $(EXAMPLES_DIR)/frames/*.json; do \
		ajv validate -s $(ENVELOPE_SCHEMA) -d $$ex --spec=draft2020 -r $(COMMON_SCHEMA) || exit 1; \
	done

validate-methods: ## Validate method content examples in examples/methods/
	@for ex in $(EXAMPLES_DIR)/methods/*.json; do \
		base=$$(basename $$ex .json); \
		ajv validate -s $(SCHEMAS_DIR)/methods/$$base.schema.json -d $$ex --spec=draft2020 -r $(COMMON_SCHEMA) || exit 1; \
	done

validate-events: ## Validate event content examples in examples/events/
	@for ex in $(EXAMPLES_DIR)/events/*.json; do \
		base=$$(basename $$ex .json); \
		ajv validate -s $(SCHEMAS_DIR)/events/$$base.schema.json -d $$ex --spec=draft2020 -r $(COMMON_SCHEMA) || exit 1; \
	done

# On-disk file formats (e.g. a plugin's manifest.json) are $defs in common, not
# standalone schemas. ajv-cli can't take a $def as the root schema, so each
# example is validated through a one-line wrapper that $refs the def whose
# PascalCase name matches the example's snake_case file name.
validate-files: ## Validate on-disk file examples in examples/files/ against their common $def
	@tmp=$$(mktemp -d); trap 'rm -rf "$$tmp"' EXIT; \
	for ex in $(EXAMPLES_DIR)/files/*.json; do \
		base=$$(basename $$ex .json); \
		def=$$(echo $$base | awk 'BEGIN{FS="_";OFS=""} { for(i=1;i<=NF;i++) $$i = toupper(substr($$i,1,1)) substr($$i,2) }1'); \
		printf '{"$$ref":"https://keyforge.dev/schemas/v1/common.schema.json#/$$defs/%s"}' $$def > $$tmp/$$def.json; \
		ajv validate -s $$tmp/$$def.json -d $$ex --spec=draft2020 -r $(COMMON_SCHEMA) || exit 1; \
	done

clean: ## Remove TS and Python package build output
	rm -rf ts/dist py/dist
	@echo "✓ Cleaned ts/dist/ and py/dist/"
