# AUTO-GENERATED by 'make generate-py'. DO NOT EDIT BY HAND.

"""Types for the KeyForge WebSocket protocol, generated from its JSON Schemas."""

from ._json import JsonObject, JsonValue
from .common_schema import (
    DeviceID,
    InputKind,
    InputAction,
    InputEvent,
    Action,
    SendKeysActionParams,
    LaunchAppActionParams,
    DelayActionParams,
    MacroActionParams,
    ToggleActionParams,
    Binding,
    InputLayout,
    DeviceRotation,
    Color,
    InputColor,
    AutoSwitchRule,
    InputFilter,
    PluginID,
    PluginLaunchInfo,
    PluginCommand,
    SetColorActionParams,
    Profile,
    ExportedProfile,
    Input,
    Device,
    ParamSpec,
    Entrypoint,
    PluginAction,
    PluginManifest,
    InstalledPlugin,
)
from .envelope_schema import (
    Request,
    ResponseOk,
    Error,
    Event,
    ResponseErr,
    Response,
    Envelope,
)
from .methods.create_profile_schema import (
    MethodCreateProfile,
    Params as CreateProfileParams,
    Result as CreateProfileResult,
)
from .methods.delete_profile_schema import (
    MethodDeleteProfile,
    Params as DeleteProfileParams,
    Result as DeleteProfileResult,
)
from .methods.duplicate_profile_schema import (
    MethodDuplicateProfile,
    Params as DuplicateProfileParams,
    Result as DuplicateProfileResult,
)
from .methods.export_profile_schema import (
    MethodExportProfile,
    Params as ExportProfileParams,
    Result as ExportProfileResult,
)
from .methods.get_auto_switch_schema import (
    MethodGetAutoSwitch,
    Result as GetAutoSwitchResult,
)
from .methods.hello_schema import (
    MethodHello,
    Params as HelloParams,
    PeerInfo,
    Result as HelloResult,
)
from .methods.import_profile_schema import (
    MethodImportProfile,
    Params as ImportProfileParams,
    Result as ImportProfileResult,
)
from .methods.inspect_plugin_schema import (
    MethodInspectPlugin,
    Params as InspectPluginParams,
    Result as InspectPluginResult,
)
from .methods.install_plugin_schema import (
    MethodInstallPlugin,
    Params as InstallPluginParams,
    Result as InstallPluginResult,
)
from .methods.list_actions_schema import (
    ActionDescriptor,
    MethodListActions,
    Result as ListActionsResult,
)
from .methods.list_bindings_schema import (
    MethodListBindings,
    Result as ListBindingsResult,
)
from .methods.list_devices_schema import (
    MethodListDevices,
    Result as ListDevicesResult,
)
from .methods.list_plugins_schema import (
    MethodListPlugins,
    Result as ListPluginsResult,
)
from .methods.list_profiles_schema import (
    MethodListProfiles,
    Result as ListProfilesResult,
)
from .methods.rename_profile_schema import (
    MethodRenameProfile,
    Params as RenameProfileParams,
)
from .methods.set_active_profile_schema import (
    MethodSetActiveProfile,
    Params as SetActiveProfileParams,
    Result as SetActiveProfileResult,
)
from .methods.set_auto_switch_schema import (
    MethodSetAutoSwitch,
    Params as SetAutoSwitchParams,
    Result as SetAutoSwitchResult,
)
from .methods.set_binding_schema import (
    MethodSetBinding,
    Params as SetBindingParams,
)
from .methods.set_device_rotation_schema import (
    MethodSetDeviceRotation,
    Params as SetDeviceRotationParams,
)
from .methods.set_input_color_schema import (
    MethodSetInputColor,
    Params as SetInputColorParams,
)
from .methods.uninstall_plugin_schema import (
    MethodUninstallPlugin,
    Params as UninstallPluginParams,
)
from .events.action_invoked_schema import (
    Action as ActionInvokedAction,
    Data as ActionInvokedData,
    EventActionInvoked,
)
from .events.active_profile_changed_schema import (
    Data as ActiveProfileChangedData,
    EventActiveProfileChanged,
)
from .events.input_schema import (
    EventInput,
)

type GetAutoSwitchParams = JsonObject
type ListActionsParams = JsonObject
type ListBindingsParams = JsonObject
type ListDevicesParams = JsonObject
type ListPluginsParams = JsonObject
type ListProfilesParams = JsonObject
type RenameProfileResult = JsonObject
type SetBindingResult = JsonObject
type SetDeviceRotationResult = JsonObject
type SetInputColorResult = JsonObject
type UninstallPluginResult = JsonObject
type InputData = InputEvent

__all__ = [
    "Action",
    "ActionDescriptor",
    "ActionInvokedAction",
    "ActionInvokedData",
    "ActiveProfileChangedData",
    "AutoSwitchRule",
    "Binding",
    "Color",
    "CreateProfileParams",
    "CreateProfileResult",
    "DelayActionParams",
    "DeleteProfileParams",
    "DeleteProfileResult",
    "Device",
    "DeviceID",
    "DeviceRotation",
    "DuplicateProfileParams",
    "DuplicateProfileResult",
    "Entrypoint",
    "Envelope",
    "Error",
    "Event",
    "EventActionInvoked",
    "EventActiveProfileChanged",
    "EventInput",
    "ExportProfileParams",
    "ExportProfileResult",
    "ExportedProfile",
    "GetAutoSwitchParams",
    "GetAutoSwitchResult",
    "HelloParams",
    "HelloResult",
    "ImportProfileParams",
    "ImportProfileResult",
    "Input",
    "InputAction",
    "InputColor",
    "InputData",
    "InputEvent",
    "InputFilter",
    "InputKind",
    "InputLayout",
    "InspectPluginParams",
    "InspectPluginResult",
    "InstallPluginParams",
    "InstallPluginResult",
    "InstalledPlugin",
    "JsonObject",
    "JsonValue",
    "LaunchAppActionParams",
    "ListActionsParams",
    "ListActionsResult",
    "ListBindingsParams",
    "ListBindingsResult",
    "ListDevicesParams",
    "ListDevicesResult",
    "ListPluginsParams",
    "ListPluginsResult",
    "ListProfilesParams",
    "ListProfilesResult",
    "MacroActionParams",
    "MethodCreateProfile",
    "MethodDeleteProfile",
    "MethodDuplicateProfile",
    "MethodExportProfile",
    "MethodGetAutoSwitch",
    "MethodHello",
    "MethodImportProfile",
    "MethodInspectPlugin",
    "MethodInstallPlugin",
    "MethodListActions",
    "MethodListBindings",
    "MethodListDevices",
    "MethodListPlugins",
    "MethodListProfiles",
    "MethodRenameProfile",
    "MethodSetActiveProfile",
    "MethodSetAutoSwitch",
    "MethodSetBinding",
    "MethodSetDeviceRotation",
    "MethodSetInputColor",
    "MethodUninstallPlugin",
    "ParamSpec",
    "PeerInfo",
    "PluginAction",
    "PluginCommand",
    "PluginID",
    "PluginLaunchInfo",
    "PluginManifest",
    "Profile",
    "RenameProfileParams",
    "RenameProfileResult",
    "Request",
    "Response",
    "ResponseErr",
    "ResponseOk",
    "SendKeysActionParams",
    "SetActiveProfileParams",
    "SetActiveProfileResult",
    "SetAutoSwitchParams",
    "SetAutoSwitchResult",
    "SetBindingParams",
    "SetBindingResult",
    "SetColorActionParams",
    "SetDeviceRotationParams",
    "SetDeviceRotationResult",
    "SetInputColorParams",
    "SetInputColorResult",
    "ToggleActionParams",
    "UninstallPluginParams",
    "UninstallPluginResult",
]
