# AUTO-GENERATED by 'make generate-py'. DO NOT EDIT BY HAND.
"""JSON values for the open objects of the schema (Action.params, Error.details, ...)."""

type JsonValue = str | int | float | bool | None | list[JsonValue] | dict[str, JsonValue]
type JsonObject = dict[str, JsonValue]
