# generated by datamodel-codegen:
#   filename:  common.schema.json

from typing import Literal, NotRequired, TypedDict

from ._json import JsonObject


type DeviceID = str
"""
Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
"""


type InputKind = Literal['key', 'encoder']
"""
Kind of physical input.
"""


type InputAction = Literal['press', 'release', 'rotate_cw', 'rotate_ccw', 'click']
"""
What happened on the input.
"""


class InputEvent(TypedDict, closed=True):
    """
    A single hardware event coming from a HID device.
    """

    device_id: DeviceID
    kind: InputKind
    input_id: str
    """
    Logical identifier of the input within the device (e.g. 'key_0x04', 'encoder_0'). Matches Device.inputs[].id.
    """
    action: InputAction
    timestamp_ms: int
    """
    Unix epoch in milliseconds when the event was captured by the daemon.
    """


class Action(TypedDict, closed=True):
    """
    An executable action bound to an input.
    """

    type: str
    """
    Action type. Built-ins are well-known; plugin actions use 'plugin.<plugin_id>.<action_id>'. Plugin ids are reverse-DNS (they contain dots) and action ids never do, so the action id is everything after the last dot.
    """
    params: NotRequired[JsonObject]
    """
    Action-specific parameters. Schema depends on 'type'. The daemon validates them against the per-type ActionParams definition (e.g. DelayActionParams for type 'delay').
    """


class SendKeysActionParams(TypedDict, closed=True):
    """
    Params for the built-in 'send_keys' action: types a key combination.
    """

    keys: str
    """
    Key combination to send, e.g. 'Ctrl+Shift+S'.
    """


class LaunchAppActionParams(TypedDict, closed=True):
    """
    Params for the built-in 'launch_app' action: launches an application.
    """

    path: str
    """
    Absolute path to the application or executable to launch.
    """


class DelayActionParams(TypedDict, closed=True):
    """
    Params for the built-in 'delay' action: waits for the given duration. Mainly useful as a step inside a macro.
    """

    ms: int
    """
    Milliseconds to wait before continuing.
    """


class MacroActionParams(TypedDict, closed=True):
    """
    Params for the built-in 'macro' action: runs a sequence of actions in order. The schema allows any Action as a step; the daemon rejects steps whose type is 'macro' or 'toggle'.
    """

    steps: list[Action]
    """
    Actions to run in order. Must contain at least one step.
    """


class ToggleActionParams(TypedDict, closed=True):
    """
    Params for the built-in 'toggle' action: alternates between two lists of actions, one per firing. The first firing runs 'on', the next one 'off', then 'on' again, and so on. Each list runs in order like a macro, stopping at the first failure. The state is kept in memory per binding: it starts at 'on' when the daemon starts and when the binding is saved (set_binding), and it is not reset when the active profile changes. The state only advances when every step of the list succeeded, so a failed 'on' is retried on the next firing; a plugin step counts as succeeded once action_invoked is sent, since delivery is fire-and-forget. The schema allows any Action as a step; the daemon rejects steps whose type is 'macro' or 'toggle', and a toggle can't be a macro step either.
    """

    on: list[Action]
    """
    Actions run on the first firing and every other one after it. Must contain at least one step.
    """
    off: list[Action]
    """
    Actions run on the second firing and every other one after it. Must contain at least one step.
    """


class Binding(TypedDict, closed=True):
    """
    Maps an input on a specific device to an action.
    """

    device_id: DeviceID
    input_id: str
    trigger: InputAction
    action: Action


class InputLayout(TypedDict, closed=True):
    """
    Physical position and size of an input, in key units (1 = one standard key). Fractions are allowed (e.g. x: 5.5 leaves a gap before a column of encoders). Coordinates are in the device's canonical orientation, defined by the daemon's device catalog: the origin is the top-left corner and y grows downwards. This is a coordinate system, not how the user has the device on the desk (that is Device.rotation). The shape is not modeled: clients derive it from Input.kind (key = rectangle, encoder = circle). Clients can draw a device only when every one of its inputs has a layout; otherwise they fall back to a view without positions (e.g. a list). Prior art: the {x, y, w, h} key model of QMK/VIA info.json.
    """

    x: float
    """
    Horizontal position of the input's top-left corner, in key units.
    """
    y: float
    """
    Vertical position of the input's top-left corner, in key units. Grows downwards.
    """
    w: NotRequired[float]
    """
    Width in key units. Absent means 1.
    """
    h: NotRequired[float]
    """
    Height in key units. Absent means 1.
    """


type DeviceRotation = Literal[0, 90, 180, 270]
"""
Clockwise rotation, in degrees, applied to the canonical orientation of a device's layout so clients show it the way the user has the device on the desk. Presentation only: bindings and colors stay tied to the physical input (input_id) and do not change when the device is rotated. It is a per-device preference, not a per-profile one: switching profiles does not change it. Set through set_device_rotation and exposed in Device.rotation, where absent means 0.
"""


type Color = str
"""
RGB color as a '#RRGGBB' hex string. Accepted in any case; the daemon stores and returns it lowercase, so clients can compare colors as strings. '#000000' turns the LED off. Hardware-agnostic: the daemon translates it to whatever the device understands (e.g. switching the device to a per-key lighting mode first).
"""


class InputColor(TypedDict, closed=True):
    """
    LED color assigned to one input of a device.
    """

    device_id: DeviceID
    input_id: str
    """
    Logical identifier of the input within the device. Matches Device.inputs[].id.
    """
    color: Color


class AutoSwitchRule(TypedDict, closed=True):
    """
    Maps a foreground application to the profile that should become active while that app is frontmost. When the frontmost app matches no rule, the active profile is left unchanged (sticky behavior); there is no fallback profile.
    """

    app: str
    """
    OS-native application identifier: bundle id on macOS, executable name on Linux/Windows. Opaque string, not portable across OSes; the daemon matches it verbatim against the frontmost app.
    """
    profile_id: str
    """
    Identifier of the profile to activate when this app is frontmost. Must reference an existing profile: set_auto_switch rejects unknown ids with PROFILE_NOT_FOUND, and delete_profile removes the rules pointing to the deleted profile.
    """


class InputFilter(TypedDict, closed=True):
    """
    Narrows which inputs a ParamSpec of type 'input' lets the user pick. Only valid with type 'input': a ParamSpec of any other type that carries it is rejected. Absent means any input of the device.
    """

    kinds: NotRequired[list[InputKind]]
    """
    Only inputs of these kinds. Absent means any kind.
    """
    rgb: NotRequired[bool]
    """
    true: only inputs with an LED (Input.rgb). false or absent: no filtering by LED.
    """


type PluginID = str
"""
Globally unique plugin identifier in reverse-DNS form (e.g. 'dev.jonidg.spotify'). Lowercase, at least two dot-separated segments, each starting with a letter. Used as the install folder name and as <plugin_id> in Action.type.
"""


class PluginLaunchInfo(TypedDict, closed=True):
    """
    Connection info the daemon hands to a plugin process it spawns, serialized as JSON in the KEYFORGE_PLUGIN_INFO environment variable (an env var rather than CLI args, so the token is not visible in the process list). The plugin connects to ws_url, sends hello with client.name set to plugin_id, and must exit when that connection closes.
    """

    plugin_id: PluginID
    """
    Id of the plugin being launched (its manifest id).
    """
    ws_url: str
    """
    WebSocket URL to connect to, including the per-plugin auth token as a query param. Treat it as a secret: the token identifies the plugin to the daemon and is distinct from the GUI's session token.
    """
    protocol_version: Literal['1']
    """
    Protocol major version the daemon speaks. The plugin sends it back in hello. Currently '1'.
    """


class PluginCommand(TypedDict, closed=True):
    """
    Executable plus arguments used to start a plugin process.
    """

    path: str
    """
    Executable to run. A path containing '/' is resolved relative to the plugin root; a bare name (e.g. 'node') is looked up on the PATH. Always use '/' as separator, also on Windows; absolute paths, '\\' and ':' are not allowed.
    """
    args: NotRequired[list[str]]
    """
    Arguments passed to the executable.
    """


class SetColorActionParams(TypedDict, closed=True):
    """
    Params for the built-in 'set_color' action: paints the LED of an input. Fails when it runs if the target input is unknown or has no LED (the device may be disconnected when the binding is saved, so the daemon checks it then). device_id is the device of input_id: absent means the device that fired the action, and it is only valid together with input_id (device_id alone is rejected when the binding is saved).
    """

    color: Color
    input_id: NotRequired[str]
    """
    Input to paint. Matches Device.inputs[].id. Absent means the input that fired the action; if nothing fired it (e.g. a test run from the GUI), the action fails. list_actions advertises it as a ParamSpec of type 'input' with input_filter {rgb: true}, which only offers inputs of the device that fired the action; when device_id is set, input_id refers to that other device, so clients should show it as-is instead of resolving it on the binding's device.
    """
    device_id: NotRequired[DeviceID]
    persist: NotRequired[bool]
    """
    false (default): paint only. The active profile's colors are untouched, Input.color keeps reporting the profile's color, and the profile's color comes back when a profile becomes active or the device reconnects. true: also write the color into the active profile, same as set_input_color.
    """


class Profile(TypedDict, closed=True):
    """
    A named set of bindings. The daemon keeps exactly one profile active at a time; switching profiles swaps the active binding set.
    """

    id: str
    """
    Stable server-generated identifier for the profile.
    """
    name: str
    """
    Human-friendly profile name.
    """
    bindings: list[Binding]
    """
    Bindings that belong to this profile.
    """
    colors: NotRequired[list[InputColor]]
    """
    LED colors this profile paints on RGB-capable inputs, applied by the daemon whenever the profile becomes active. An RGB input with no entry here is turned off. At most one entry per (device_id, input_id); the daemon enforces uniqueness. Absent means no colors.
    """


class ExportedProfile(TypedDict, closed=True):
    """
    Portable, on-disk representation of a profile, written by export_profile and read by import_profile. Carries no server-local id: the id is meaningless outside the originating installation, so import always assigns a fresh one. The 'version' field lets readers detect and adapt to format changes.
    """

    format: Literal['keyforge.profile']
    """
    Magic marker identifying the file as a KeyForge profile export.
    """
    version: Literal[1]
    """
    Export format version. Currently 1; bumped if the on-disk shape changes.
    """
    name: str
    """
    Human-friendly profile name.
    """
    bindings: list[Binding]
    """
    Bindings that belong to the exported profile.
    """
    colors: NotRequired[list[InputColor]]
    """
    LED colors of the exported profile. Same semantics as Profile.colors.
    """


class Input(TypedDict, closed=True):
    """
    A single physical input exposed by a device (a key or an encoder).
    """

    id: str
    """
    Logical identifier of the input within the device (e.g. 'key_0x04', 'encoder_0'). Matches InputEvent.input_id and Binding.input_id.
    """
    kind: InputKind
    label: NotRequired[str]
    """
    Fixed name of the input (e.g. 'Enter', 'Play') that clients show as-is in any orientation. When absent, clients name the input by position: they number inputs per kind in reading order of the current view, sorting by each input's top-left corner after applying Device.rotation (y first, then x), so 'Key 1' is always the top-left key as the device sits on the desk. If the device has no complete layout, they number inputs per kind in the order list_devices returns them. Catalogs should not send positional labels like 'Key 1': they would be wrong once the device is rotated.
    """
    layout: NotRequired[InputLayout]
    rgb: NotRequired[bool]
    """
    Whether the input has an RGB LED the daemon can drive through set_input_color. Absent means false.
    """
    color: NotRequired[Color]
    """
    Color the active profile paints on this input. Only set on RGB inputs that have a color in the active profile; absent means the LED is off.
    """


class Device(TypedDict, closed=True):
    """
    A HID device known to the daemon. Returned by list_devices.
    """

    id: DeviceID
    vendor_id: str
    """
    USB Vendor ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
    """
    product_id: str
    """
    USB Product ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
    """
    manufacturer: NotRequired[str]
    """
    Manufacturer string from the HID descriptor. May be missing on cheap/clone devices.
    """
    product: NotRequired[str]
    """
    Product name string from the HID descriptor.
    """
    serial_number: NotRequired[str]
    """
    Serial number string from the HID descriptor. Not all HID devices expose one.
    """
    path: str
    """
    OS-opaque path used by the HID library to (re)open the device. Format varies per OS; clients should treat it as an opaque token.
    """
    inputs: list[Input]
    """
    Inputs (keys/encoders) the daemon knows this device exposes. Empty for unrecognized devices the daemon can't map.
    """
    rotation: NotRequired[DeviceRotation]


class ParamSpec(TypedDict, closed=True):
    """
    Describes one action parameter so a client can render an input for it.
    """

    name: str
    """
    Param key written into Action.params. Unique within the action.
    """
    label: str
    """
    Human-friendly field label.
    """
    type: Literal['string', 'boolean', 'color', 'input']
    """
    Param value type, which sets the JSON type written into Action.params: 'string' a string, 'boolean' a boolean, 'color' a Color ('#RRGGBB' string, rendered as a color picker), 'input' a string holding the Input.id of an input on the same device as the binding that fires the action. An optional boolean that is absent means false. placeholder only applies to 'string' and 'input'. 'input' is rendered as a picker listing that device's inputs (narrowed by input_filter), named and ordered as in the visual editor: Input.label, or numbered per kind in reading order of the rotated view. An optional 'input' that is absent means nothing was picked; each action defines what that means (for set_color, the input that fired the action). The stored value is always the Input.id (the physical input), never a position or a numbered label: Device.rotation is presentation only, so rotating the device after saving does not change which physical input the param targets, while the label the picker shows for it does change (at 180 degrees the top-left key becomes the bottom-right one). Clients translate both ways with the current rotation: label to id when picking, id to label when showing a saved value. Whether the id exists on the device is checked when the action runs, not when the binding is saved (the device may be disconnected).
    """
    required: bool
    placeholder: NotRequired[str]
    """
    For 'string': placeholder/example shown in the text field. For 'input': label of the picker's 'nothing picked' option in an optional param, describing what the action does when no input is picked (e.g. set_color: 'This key (the one that fired)'); a required 'input' param has no such option, so clients ignore it. Does not apply to 'boolean' or 'color'.
    """
    input_filter: NotRequired[InputFilter]


class Entrypoint(TypedDict, closed=True):
    """
    Command the daemon runs to start the plugin, per OS (keys match Go's GOOS). The plugin supports exactly the OSes listed here.
    """

    darwin: NotRequired[PluginCommand]
    linux: NotRequired[PluginCommand]
    windows: NotRequired[PluginCommand]


class PluginAction(TypedDict, closed=True):
    """
    An action a plugin exposes, declared in its manifest.
    """

    id: str
    """
    Action identifier, unique within the plugin. snake_case, no dots.
    """
    name: str
    """
    Human-friendly action name for the UI.
    """
    description: NotRequired[str]
    """
    Optional longer description of what the action does.
    """
    inputs: NotRequired[list[InputKind]]
    """
    Input kinds the action can be bound to. Omitted means any kind.
    """
    params: list[ParamSpec]
    """
    Params this action accepts, in display order.
    """


class PluginManifest(TypedDict, closed=True):
    """
    Contents of the manifest.json file at the root of a plugin. A plugin is distributed as a '.keyforgeplugin' file: a zip archive with manifest.json at its root (no wrapping folder) plus every file the manifest references. The daemon installs it by extracting the archive into '<config dir>/plugins/<id>/', taking the id from the manifest. All file paths in the manifest (icon, and entrypoint paths containing '/') are relative to the plugin root, use '/' as separator, and must stay inside the plugin root: the daemon rejects '..' segments and any path or archive entry that escapes the root.
    """

    manifest_version: Literal[1]
    """
    Manifest format version. Currently 1; bumped if the manifest shape changes.
    """
    id: PluginID
    """
    Globally unique reverse-DNS plugin id; install folder name and <plugin_id> in Action.type.
    """
    name: str
    """
    Human-friendly plugin name for the UI.
    """
    version: str
    """
    Plugin version (SemVer 2.0).
    """
    protocol_version: Literal['1']
    """
    Major version of the protocol the plugin speaks. Lets the daemon reject an incompatible plugin before spawning it. Currently '1'.
    """
    author: NotRequired[str]
    """
    Plugin author, shown in the UI.
    """
    description: NotRequired[str]
    """
    Short description of what the plugin does.
    """
    homepage: NotRequired[str]
    """
    URL of the plugin homepage or source repository.
    """
    category: NotRequired[str]
    """
    Category the UI groups the plugin's actions under (e.g. 'Audio', 'Streaming').
    """
    icon: NotRequired[str]
    """
    Path to the plugin icon, relative to the plugin root. No leading '/', no '\\' and no ':'.
    """
    entrypoint: Entrypoint
    """
    Command the daemon runs to start the plugin, per OS (keys match Go's GOOS). The plugin supports exactly the OSes listed here.
    """
    actions: list[PluginAction]
    """
    Actions the plugin exposes. Each becomes bindable as 'plugin.<id>.<action id>'.
    """


class InstalledPlugin(TypedDict, closed=True):
    """
    A plugin installed in the daemon, with the state of its process.
    """

    manifest: PluginManifest
    status: Literal['starting', 'running', 'stopped', 'error']
    """
    State of the plugin process: 'starting' (spawned, hello not received yet), 'running' (connected), 'stopped' (not running, e.g. exited cleanly) or 'error' (failed to start or crashed; see 'error').
    """
    error: NotRequired[str]
    """
    Human-readable reason why the plugin failed. The daemon sets it only when status is 'error' (not enforced by the schema).
    """
