# generated by datamodel-codegen:
#   filename:  envelope.schema.json

from typing import Literal, NotRequired, TypedDict

from ._json import JsonObject


class Request(TypedDict, closed=True):
    """
    Client -> server. Expects a correlated Response with the same id.
    """

    type: Literal['request']
    id: str
    """
    Client-generated correlation id (UUID v4 or nanoid).
    """
    method: str
    """
    Method name in snake_case.
    """
    params: JsonObject
    """
    Method-specific arguments. Refined by the schema in schemas/methods/<method>.schema.json.
    """


class ResponseOk(TypedDict, closed=True):
    type: Literal['response']
    id: str
    """
    Echo of the original Request.id.
    """
    ok: Literal[True]
    data: JsonObject
    """
    Method-specific result. Refined by the schema in schemas/methods/<method>.schema.json.
    """


class Error(TypedDict, closed=True):
    """
    Failure payload returned in a Response with ok=false.
    """

    code: str
    """
    Stable, machine-readable error code in SCREAMING_SNAKE_CASE.
    """
    message: str
    """
    Human-readable error message. Free form, may be localized in future versions.
    """
    details: NotRequired[JsonObject]
    """
    Optional structured context for debugging.
    """


class Event(TypedDict, closed=True):
    """
    Server -> client, no correlation. Stream of hardware events or daemon notifications.
    """

    type: Literal['event']
    name: str
    """
    Event name in snake_case.
    """
    data: JsonObject
    """
    Event-specific payload. Refined by the schema in schemas/events/<name>.schema.json.
    """


class ResponseErr(TypedDict, closed=True):
    type: Literal['response']
    id: str
    """
    Echo of the original Request.id.
    """
    ok: Literal[False]
    error: Error


type Response = ResponseOk | ResponseErr
"""
Server -> client. Discriminated by 'ok'.
"""


type Envelope = Request | Response | Event
"""
Wire-level frame exchanged over the WebSocket transport. Every frame is one of three shapes discriminated by the 'type' field. Inner 'params'/'data'/'error' are intentionally generic here; method- and event-specific schemas refine them in a second validation pass.
"""
