"""Post-process datamodel-codegen output into the keyforge_protocol package.

Run by `make generate-py` right after datamodel-codegen. It:

- imports TypedDict from `typing` instead of `typing_extensions` (PEP 728
  `closed=True` is in the stdlib since 3.15), so the package has no runtime
  dependencies;
- replaces `dict[str, Any]` (open objects and empty `{}` objects) with the
  `JsonObject` alias and fails if any other `Any` is left;
- drops the `CommonTypes` alias that the root of common.schema.json produces;
- writes `_json.py`, `py.typed` and the barrel `__init__.py`.

Usage: python scripts/py_postprocess.py <package dir> <schemas dir>
"""

import ast
import json
import re
import sys
from pathlib import Path

GENERATED_HEADER = "# AUTO-GENERATED by 'make generate-py'. DO NOT EDIT BY HAND.\n"

JSON_MODULE = (
    GENERATED_HEADER
    + '"""JSON values for the open objects of the schema (Action.params, Error.details, ...)."""\n'
    + "\n"
    + "type JsonValue = str | int | float | bool | None | list[JsonValue] | dict[str, JsonValue]\n"
    + "type JsonObject = dict[str, JsonValue]\n"
)

# The root of common.schema.json has no type, so the generator emits
# `type CommonTypes = Any` followed by the schema description as a docstring.
COMMON_ROOT = re.compile(r'^type CommonTypes = Any\n(""".*?"""\n)?', re.MULTILINE | re.DOTALL)
TYPING_IMPORT = re.compile(r"^from typing import (.+)$", re.MULTILINE)
TYPING_EXTENSIONS_IMPORT = re.compile(r"^from typing_extensions import (.+)$", re.MULTILINE)
MULTILINE_TYPING_IMPORT = re.compile(r"^from typing(_extensions)? import \(", re.MULTILINE)


def pascal(snake: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in snake.split("_"))


def rewrite_module(path: Path, depth: int) -> None:
    src = path.read_text()
    src = COMMON_ROOT.sub("", src)
    src = src.replace("dict[str, Any]", "JsonObject")
    uses_json = "JsonObject" in src

    if MULTILINE_TYPING_IMPORT.search(src):
        sys.exit(f"py_postprocess: {path} has a multi-line typing import; teach rewrite_module to parse it")
    # Everything the generator takes from typing_extensions (TypedDict for
    # closed=, NotRequired, ...) is in the stdlib typing module since 3.15.
    names: set[str] = set()
    for pattern in (TYPING_IMPORT, TYPING_EXTENSIONS_IMPORT):
        match = pattern.search(src)
        if match:
            names.update(n.strip() for n in match.group(1).split(","))
            src = pattern.sub("", src, count=1)
    names.discard("Any")

    dots = "." * depth
    relative = f"from {dots} import common_schema\n"
    json_import = f"from {dots}_json import JsonObject\n"
    block = f"from typing import {', '.join(sorted(names))}\n" if names else ""
    if uses_json and relative in src:
        src = src.replace(relative, relative + json_import)
    elif uses_json:
        block += "\n" + json_import
    # The header comments end at the first blank line; the rebuilt imports go
    # right after them, and the blank lines left by the removed ones collapse.
    head, _, body = src.partition("\n\n")
    body = body.lstrip("\n")
    # One blank line before the generator's own relative imports, two before code.
    separator = "\n" if body.startswith("from ") else "\n\n"
    src = f"{head}\n\n{block}{separator}{body}"
    src = re.sub(r"\n{4,}", "\n\n\n", src)

    nodes = list(ast.walk(ast.parse(src)))
    if any(isinstance(node, ast.ImportFrom) and node.module == "typing_extensions" for node in nodes):
        sys.exit(f"py_postprocess: {path} still imports typing_extensions, which is not a declared dependency")
    if any(isinstance(node, ast.Name) and node.id == "Any" for node in nodes):
        sys.exit(
            f"py_postprocess: {path} still uses Any; extend the JsonObject rewrite"
        )
    path.write_text(src)


def top_level_names(tree: ast.Module) -> list[str]:
    names: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            names.append(node.name)
        elif isinstance(node, ast.TypeAlias) and isinstance(node.name, ast.Name):
            names.append(node.name.id)
    return names


def field_annotations(tree: ast.Module, class_name: str) -> dict[str, ast.expr]:
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            return {
                stmt.target.id: stmt.annotation
                for stmt in node.body
                if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name)
            }
    sys.exit(f"py_postprocess: class {class_name} not found")


def from_import(module: str, names: list[str]) -> str:
    body = "".join(f"    {name},\n" for name in names)
    return f"from .{module} import (\n{body})"


class Barrel:
    def __init__(self) -> None:
        self.imports: list[str] = []
        self.aliases: list[str] = []
        self.exported: set[str] = set()

    def export(self, name: str, where: str) -> None:
        if name in self.exported:
            sys.exit(
                f"py_postprocess: barrel name {name} from {where} is already taken"
            )
        self.exported.add(name)

    def reexport_all(self, module: str, tree: ast.Module) -> None:
        names = top_level_names(tree)
        for name in names:
            self.export(name, module)
        self.imports.append(from_import(module, names))

    def add_message(
        self,
        package: str,
        base: str,
        kind: str,
        fields: tuple[str, ...],
        local_defs: set[str],
        tree: ast.Module,
    ) -> None:
        """Export the Method*/Event* type of one method or event module.

        Its params/result/data become <Pascal>Params/Result/Data, $defs local to
        the schema keep their name and other nested objects get the <Pascal>
        prefix, so names never depend on which modules happen to collide.
        """
        module = f"{package}.{base}_schema"
        prefix = pascal(base)
        top = f"{kind}{prefix}"
        annotations = field_annotations(tree, top)
        classes = set(top_level_names(tree))
        renames = {top: top}
        for field in fields:
            annotation = annotations.get(field)
            if annotation is None:
                continue
            alias = f"{prefix}{field.capitalize()}"
            if isinstance(annotation, ast.Name) and annotation.id in renames:
                # Same local class as an earlier field (e.g. params and result).
                self.export(alias, module)
                self.aliases.append(f"type {alias} = {renames[annotation.id]}")
            elif isinstance(annotation, ast.Name) and annotation.id in classes:
                renames[annotation.id] = alias
            else:
                expr = ast.unparse(annotation).replace("common_schema.", "")
                self.export(alias, module)
                self.aliases.append(f"type {alias} = {expr}")
        for name in classes - renames.keys():
            renames[name] = name if name in local_defs else f"{prefix}{name}"
        parts = []
        for name in sorted(renames):
            self.export(renames[name], module)
            parts.append(
                name if renames[name] == name else f"{name} as {renames[name]}"
            )
        self.imports.append(from_import(module, parts))

    def render(self) -> str:
        lines = [
            GENERATED_HEADER,
            '"""Types for the KeyForge WebSocket protocol, generated from its JSON Schemas."""',
            "",
        ]
        lines += ["from ._json import JsonObject, JsonValue", *self.imports, ""]
        lines += self.aliases
        exported = sorted(self.exported | {"JsonObject", "JsonValue"})
        lines += ["", "__all__ = [", *(f'    "{name}",' for name in exported), "]", ""]
        return "\n".join(lines)


def main() -> None:
    pkg, schemas = Path(sys.argv[1]), Path(sys.argv[2])
    (pkg / "_json.py").write_text(JSON_MODULE)
    (pkg / "py.typed").write_text("")

    barrel = Barrel()
    processed: set[Path] = set()
    for module in ("common_schema", "envelope_schema"):
        path = pkg / f"{module}.py"
        rewrite_module(path, depth=1)
        processed.add(path)
        barrel.reexport_all(module, ast.parse(path.read_text()))

    for package, kind, fields in (
        ("methods", "Method", ("params", "result")),
        ("events", "Event", ("data",)),
    ):
        for schema in sorted((schemas / package).glob("*.schema.json")):
            base = schema.name.removesuffix(".schema.json")
            path = pkg / package / f"{base}_schema.py"
            rewrite_module(path, depth=2)
            processed.add(path)
            local_defs = set(json.loads(schema.read_text()).get("$defs", {}))
            barrel.add_message(
                package, base, kind, fields, local_defs, ast.parse(path.read_text())
            )

    # The generator emits a module for every schema under schemas/; one this
    # script doesn't know would skip the rewrites above and the barrel.
    unknown = sorted(str(path) for path in set(pkg.rglob("*_schema.py")) - processed)
    if unknown:
        sys.exit(f"py_postprocess: no rule for generated modules {unknown}; add them to main()")

    (pkg / "__init__.py").write_text(barrel.render())


if __name__ == "__main__":
    main()
