// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package protocol

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "unicode/utf8"

// An executable action bound to an input.
type Action struct {
	// Action-specific parameters. Schema depends on 'type'. The daemon validates them
	// against the per-type ActionParams definition (e.g. DelayActionParams for type
	// 'delay').
	Params ActionParams `json:"params,omitempty,omitzero" yaml:"params,omitempty" mapstructure:"params,omitempty"`

	// Action type. Built-ins are well-known; plugin actions use
	// 'plugin.<plugin_id>.<action_id>'.
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// Describes a bindable action type and the params it accepts.
type ActionDescriptor struct {
	// Optional longer description of what the action does.
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Human-friendly action name for the UI.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Params this action accepts, in display order.
	Params []ParamSpec `json:"params" yaml:"params" mapstructure:"params"`

	// Action type, as used in Action.type (e.g. 'launch_app').
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionDescriptor) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ActionDescriptor: required")
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in ActionDescriptor: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ActionDescriptor: required")
	}
	type Plain ActionDescriptor
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if utf8.RuneCountInString(string(plain.Type)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "type", 1)
	}
	*j = ActionDescriptor(plain)
	return nil
}

// Action-specific parameters. Schema depends on 'type'. The daemon validates them
// against the per-type ActionParams definition (e.g. DelayActionParams for type
// 'delay').
type ActionParams map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Action) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Action: required")
	}
	type Plain Action
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Action(plain)
	return nil
}

// Pushed by the daemon whenever the active profile changes on the server's own
// initiative (today: auto-switch by foreground app). Lets clients stay in sync
// without polling. Not emitted in response to a client's set_active_profile
// request, which already returns the new id.
type ActiveProfileChangedSchemaJson struct {
	// Data corresponds to the JSON schema field "data".
	Data ActiveProfileChangedSchemaJsonData `json:"data" yaml:"data" mapstructure:"data"`
}

type ActiveProfileChangedSchemaJsonData struct {
	// Identifier of the now-active profile.
	ActiveProfileId string `json:"active_profile_id" yaml:"active_profile_id" mapstructure:"active_profile_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActiveProfileChangedSchemaJsonData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["active_profile_id"]; raw != nil && !ok {
		return fmt.Errorf("field active_profile_id in ActiveProfileChangedSchemaJsonData: required")
	}
	type Plain ActiveProfileChangedSchemaJsonData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.ActiveProfileId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "active_profile_id", 1)
	}
	*j = ActiveProfileChangedSchemaJsonData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActiveProfileChangedSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in ActiveProfileChangedSchemaJson: required")
	}
	type Plain ActiveProfileChangedSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ActiveProfileChangedSchemaJson(plain)
	return nil
}

// Maps a foreground application to the profile that should become active while
// that app is frontmost. When the frontmost app matches no rule, the active
// profile is left unchanged (sticky behavior); there is no fallback profile.
type AutoSwitchRule struct {
	// OS-native application identifier: bundle id on macOS, executable name on
	// Linux/Windows. Opaque string, not portable across OSes; the daemon matches it
	// verbatim against the frontmost app.
	App string `json:"app" yaml:"app" mapstructure:"app"`

	// Identifier of the profile to activate when this app is frontmost.
	ProfileId string `json:"profile_id" yaml:"profile_id" mapstructure:"profile_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AutoSwitchRule) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["app"]; raw != nil && !ok {
		return fmt.Errorf("field app in AutoSwitchRule: required")
	}
	if _, ok := raw["profile_id"]; raw != nil && !ok {
		return fmt.Errorf("field profile_id in AutoSwitchRule: required")
	}
	type Plain AutoSwitchRule
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.App)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "app", 1)
	}
	if utf8.RuneCountInString(string(plain.ProfileId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "profile_id", 1)
	}
	*j = AutoSwitchRule(plain)
	return nil
}

// Maps an input on a specific device to an action.
type Binding struct {
	// Action corresponds to the JSON schema field "action".
	Action Action `json:"action" yaml:"action" mapstructure:"action"`

	// DeviceId corresponds to the JSON schema field "device_id".
	DeviceId DeviceID `json:"device_id" yaml:"device_id" mapstructure:"device_id"`

	// InputId corresponds to the JSON schema field "input_id".
	InputId string `json:"input_id" yaml:"input_id" mapstructure:"input_id"`

	// Trigger corresponds to the JSON schema field "trigger".
	Trigger InputAction `json:"trigger" yaml:"trigger" mapstructure:"trigger"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Binding) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in Binding: required")
	}
	if _, ok := raw["device_id"]; raw != nil && !ok {
		return fmt.Errorf("field device_id in Binding: required")
	}
	if _, ok := raw["input_id"]; raw != nil && !ok {
		return fmt.Errorf("field input_id in Binding: required")
	}
	if _, ok := raw["trigger"]; raw != nil && !ok {
		return fmt.Errorf("field trigger in Binding: required")
	}
	type Plain Binding
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.InputId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "input_id", 1)
	}
	*j = Binding(plain)
	return nil
}

// Creates a new profile. The server generates the id and returns the profile with
// an empty bindings array.
type CreateProfileSchemaJson struct {
	// Params corresponds to the JSON schema field "params".
	Params CreateProfileSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result CreateProfileSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

type CreateProfileSchemaJsonParams struct {
	// Human-friendly name for the new profile.
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CreateProfileSchemaJsonParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in CreateProfileSchemaJsonParams: required")
	}
	type Plain CreateProfileSchemaJsonParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	*j = CreateProfileSchemaJsonParams(plain)
	return nil
}

type CreateProfileSchemaJsonResult struct {
	// Profile corresponds to the JSON schema field "profile".
	Profile Profile `json:"profile" yaml:"profile" mapstructure:"profile"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CreateProfileSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["profile"]; raw != nil && !ok {
		return fmt.Errorf("field profile in CreateProfileSchemaJsonResult: required")
	}
	type Plain CreateProfileSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CreateProfileSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CreateProfileSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in CreateProfileSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in CreateProfileSchemaJson: required")
	}
	type Plain CreateProfileSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CreateProfileSchemaJson(plain)
	return nil
}

// Params for the built-in 'delay' action: waits for the given duration. Mainly
// useful as a step inside a macro.
type DelayActionParams struct {
	// Milliseconds to wait before continuing.
	Ms int `json:"ms" yaml:"ms" mapstructure:"ms"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DelayActionParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ms"]; raw != nil && !ok {
		return fmt.Errorf("field ms in DelayActionParams: required")
	}
	type Plain DelayActionParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Ms {
		return fmt.Errorf("field %s: must be >= %v", "ms", 0)
	}
	*j = DelayActionParams(plain)
	return nil
}

// Deletes a profile. The daemon never deletes the last remaining profile. Deleting
// the active profile reassigns the active one, so the resulting active profile id
// is always returned.
type DeleteProfileSchemaJson struct {
	// Params corresponds to the JSON schema field "params".
	Params DeleteProfileSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result DeleteProfileSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

type DeleteProfileSchemaJsonParams struct {
	// Identifier of the profile to delete.
	Id string `json:"id" yaml:"id" mapstructure:"id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DeleteProfileSchemaJsonParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in DeleteProfileSchemaJsonParams: required")
	}
	type Plain DeleteProfileSchemaJsonParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = DeleteProfileSchemaJsonParams(plain)
	return nil
}

type DeleteProfileSchemaJsonResult struct {
	// Identifier of the profile that is active after the deletion. Unchanged unless
	// the deleted profile was the active one.
	ActiveProfileId string `json:"active_profile_id" yaml:"active_profile_id" mapstructure:"active_profile_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DeleteProfileSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["active_profile_id"]; raw != nil && !ok {
		return fmt.Errorf("field active_profile_id in DeleteProfileSchemaJsonResult: required")
	}
	type Plain DeleteProfileSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.ActiveProfileId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "active_profile_id", 1)
	}
	*j = DeleteProfileSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DeleteProfileSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in DeleteProfileSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in DeleteProfileSchemaJson: required")
	}
	type Plain DeleteProfileSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DeleteProfileSchemaJson(plain)
	return nil
}

// A HID device known to the daemon. Returned by list_devices.
type Device struct {
	// Id corresponds to the JSON schema field "id".
	Id DeviceID `json:"id" yaml:"id" mapstructure:"id"`

	// Inputs (keys/encoders) the daemon knows this device exposes. Empty for
	// unrecognized devices the daemon can't map.
	Inputs []Input `json:"inputs" yaml:"inputs" mapstructure:"inputs"`

	// Manufacturer string from the HID descriptor. May be missing on cheap/clone
	// devices.
	Manufacturer *string `json:"manufacturer,omitempty,omitzero" yaml:"manufacturer,omitempty" mapstructure:"manufacturer,omitempty"`

	// OS-opaque path used by the HID library to (re)open the device. Format varies
	// per OS; clients should treat it as an opaque token.
	Path string `json:"path" yaml:"path" mapstructure:"path"`

	// Product name string from the HID descriptor.
	Product *string `json:"product,omitempty,omitzero" yaml:"product,omitempty" mapstructure:"product,omitempty"`

	// USB Product ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x'
	// prefix).
	ProductId string `json:"product_id" yaml:"product_id" mapstructure:"product_id"`

	// Serial number string from the HID descriptor. Not all HID devices expose one.
	SerialNumber *string `json:"serial_number,omitempty,omitzero" yaml:"serial_number,omitempty" mapstructure:"serial_number,omitempty"`

	// USB Vendor ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x'
	// prefix).
	VendorId string `json:"vendor_id" yaml:"vendor_id" mapstructure:"vendor_id"`
}

// Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
type DeviceID string

// UnmarshalJSON implements json.Unmarshaler.
func (j *DeviceID) UnmarshalJSON(value []byte) error {
	type Plain DeviceID
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^VID_[0-9A-Fa-f]{4}_PID_[0-9A-Fa-f]{4}(_.+)?$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^VID_[0-9A-Fa-f]{4}_PID_[0-9A-Fa-f]{4}(_.+)?$`)
	}
	*j = DeviceID(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Device) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Device: required")
	}
	if _, ok := raw["inputs"]; raw != nil && !ok {
		return fmt.Errorf("field inputs in Device: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in Device: required")
	}
	if _, ok := raw["product_id"]; raw != nil && !ok {
		return fmt.Errorf("field product_id in Device: required")
	}
	if _, ok := raw["vendor_id"]; raw != nil && !ok {
		return fmt.Errorf("field vendor_id in Device: required")
	}
	type Plain Device
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Path)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "path", 1)
	}
	if matched, _ := regexp.MatchString(`^[0-9A-Fa-f]{4}$`, string(plain.ProductId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ProductId", `^[0-9A-Fa-f]{4}$`)
	}
	if matched, _ := regexp.MatchString(`^[0-9A-Fa-f]{4}$`, string(plain.VendorId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "VendorId", `^[0-9A-Fa-f]{4}$`)
	}
	*j = Device(plain)
	return nil
}

// Creates a copy of an existing profile under a new name. The server generates a
// new id and copies the source profile's bindings. Does not change the active
// profile.
type DuplicateProfileSchemaJson struct {
	// Params corresponds to the JSON schema field "params".
	Params DuplicateProfileSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result DuplicateProfileSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

type DuplicateProfileSchemaJsonParams struct {
	// Identifier of the source profile to copy bindings from.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Human-friendly name for the new (duplicated) profile.
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DuplicateProfileSchemaJsonParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in DuplicateProfileSchemaJsonParams: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in DuplicateProfileSchemaJsonParams: required")
	}
	type Plain DuplicateProfileSchemaJsonParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	*j = DuplicateProfileSchemaJsonParams(plain)
	return nil
}

type DuplicateProfileSchemaJsonResult struct {
	// Profile corresponds to the JSON schema field "profile".
	Profile Profile `json:"profile" yaml:"profile" mapstructure:"profile"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DuplicateProfileSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["profile"]; raw != nil && !ok {
		return fmt.Errorf("field profile in DuplicateProfileSchemaJsonResult: required")
	}
	type Plain DuplicateProfileSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DuplicateProfileSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DuplicateProfileSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in DuplicateProfileSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in DuplicateProfileSchemaJson: required")
	}
	type Plain DuplicateProfileSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DuplicateProfileSchemaJson(plain)
	return nil
}

// Failure payload returned in a Response with ok=false.
type Error struct {
	// Stable, machine-readable error code in SCREAMING_SNAKE_CASE.
	Code string `json:"code" yaml:"code" mapstructure:"code"`

	// Optional structured context for debugging.
	Details ErrorDetails `json:"details,omitempty,omitzero" yaml:"details,omitempty" mapstructure:"details,omitempty"`

	// Human-readable error message. Free form, may be localized in future versions.
	Message string `json:"message" yaml:"message" mapstructure:"message"`
}

// Optional structured context for debugging.
type ErrorDetails map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Error) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["code"]; raw != nil && !ok {
		return fmt.Errorf("field code in Error: required")
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in Error: required")
	}
	type Plain Error
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Z][A-Z0-9_]*$`, string(plain.Code)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Code", `^[A-Z][A-Z0-9_]*$`)
	}
	if utf8.RuneCountInString(string(plain.Message)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "message", 1)
	}
	*j = Error(plain)
	return nil
}

// Server -> client, no correlation. Stream of hardware events or daemon
// notifications.
type Event struct {
	// Event-specific payload. Refined by the schema in
	// schemas/events/<name>.schema.json.
	Data EventData `json:"data" yaml:"data" mapstructure:"data"`

	// Event name in snake_case.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// Event-specific payload. Refined by the schema in
// schemas/events/<name>.schema.json.
type EventData map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Event) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in Event: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Event: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Event: required")
	}
	type Plain Event
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9_]*$`, string(plain.Name)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Name", `^[a-z][a-z0-9_]*$`)
	}
	*j = Event(plain)
	return nil
}

// Serializes the profile identified by 'id' as a portable ExportedProfile document
// and writes it to 'path' on the daemon host's filesystem. The exported file omits
// the server-local id. Returns the path that was written.
type ExportProfileSchemaJson struct {
	// Params corresponds to the JSON schema field "params".
	Params ExportProfileSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result ExportProfileSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

type ExportProfileSchemaJsonParams struct {
	// Identifier of the profile to export.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Filesystem path on the daemon host where the exported file is written.
	Path string `json:"path" yaml:"path" mapstructure:"path"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExportProfileSchemaJsonParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ExportProfileSchemaJsonParams: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in ExportProfileSchemaJsonParams: required")
	}
	type Plain ExportProfileSchemaJsonParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Path)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "path", 1)
	}
	*j = ExportProfileSchemaJsonParams(plain)
	return nil
}

type ExportProfileSchemaJsonResult struct {
	// Echo of the path that was written.
	Path string `json:"path" yaml:"path" mapstructure:"path"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExportProfileSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in ExportProfileSchemaJsonResult: required")
	}
	type Plain ExportProfileSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Path)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "path", 1)
	}
	*j = ExportProfileSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExportProfileSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in ExportProfileSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in ExportProfileSchemaJson: required")
	}
	type Plain ExportProfileSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ExportProfileSchemaJson(plain)
	return nil
}

// Portable, on-disk representation of a profile, written by export_profile and
// read by import_profile. Carries no server-local id: the id is meaningless
// outside the originating installation, so import always assigns a fresh one. The
// 'version' field lets readers detect and adapt to format changes.
type ExportedProfile struct {
	// Bindings that belong to the exported profile.
	Bindings []Binding `json:"bindings" yaml:"bindings" mapstructure:"bindings"`

	// Magic marker identifying the file as a KeyForge profile export.
	Format string `json:"format" yaml:"format" mapstructure:"format"`

	// Human-friendly profile name.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Export format version. Currently 1; bumped if the on-disk shape changes.
	Version int `json:"version" yaml:"version" mapstructure:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExportedProfile) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bindings"]; raw != nil && !ok {
		return fmt.Errorf("field bindings in ExportedProfile: required")
	}
	if _, ok := raw["format"]; raw != nil && !ok {
		return fmt.Errorf("field format in ExportedProfile: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ExportedProfile: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in ExportedProfile: required")
	}
	type Plain ExportedProfile
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Format != "keyforge.profile" {
		return fmt.Errorf("field %s: must be equal to %s", "format", "keyforge.profile")
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if plain.Version != 1 {
		return fmt.Errorf("field %s: must be equal to %v", "version", 1)
	}
	*j = ExportedProfile(plain)
	return nil
}

// Returns the current auto-switch configuration: the master toggle and the full
// set of app-to-profile rules. The daemon uses these to switch the active profile
// based on the foreground application.
type GetAutoSwitchSchemaJson struct {
	// No parameters in v1.
	Params GetAutoSwitchSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result GetAutoSwitchSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

// No parameters in v1.
type GetAutoSwitchSchemaJsonParams map[string]interface{}

type GetAutoSwitchSchemaJsonResult struct {
	// Master toggle. When false, the daemon ignores the rules and never
	// auto-switches.
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`

	// App-to-profile rules currently configured.
	Rules []AutoSwitchRule `json:"rules" yaml:"rules" mapstructure:"rules"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GetAutoSwitchSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["enabled"]; raw != nil && !ok {
		return fmt.Errorf("field enabled in GetAutoSwitchSchemaJsonResult: required")
	}
	if _, ok := raw["rules"]; raw != nil && !ok {
		return fmt.Errorf("field rules in GetAutoSwitchSchemaJsonResult: required")
	}
	type Plain GetAutoSwitchSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GetAutoSwitchSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GetAutoSwitchSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in GetAutoSwitchSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in GetAutoSwitchSchemaJson: required")
	}
	type Plain GetAutoSwitchSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GetAutoSwitchSchemaJson(plain)
	return nil
}

// Mandatory first request after a WebSocket connection is established. The client
// declares the protocol_version it speaks. The server either accepts
// (Response.ok=true with its own identification) or closes the connection with an
// UNSUPPORTED_PROTOCOL_VERSION error. After a successful hello no further version
// negotiation happens; the contract is fixed for the session.
type HelloSchemaJson struct {
	// Params corresponds to the JSON schema field "params".
	Params HelloSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result HelloSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

type HelloSchemaJsonParams struct {
	// Client corresponds to the JSON schema field "client".
	Client PeerInfo `json:"client" yaml:"client" mapstructure:"client"`

	// Major version of the protocol the client implements. Currently '1'.
	ProtocolVersion string `json:"protocol_version" yaml:"protocol_version" mapstructure:"protocol_version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HelloSchemaJsonParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["client"]; raw != nil && !ok {
		return fmt.Errorf("field client in HelloSchemaJsonParams: required")
	}
	if _, ok := raw["protocol_version"]; raw != nil && !ok {
		return fmt.Errorf("field protocol_version in HelloSchemaJsonParams: required")
	}
	type Plain HelloSchemaJsonParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.ProtocolVersion != "1" {
		return fmt.Errorf("field %s: must be equal to %s", "protocol_version", "1")
	}
	*j = HelloSchemaJsonParams(plain)
	return nil
}

type HelloSchemaJsonResult struct {
	// Protocol version the server agrees to speak for this session.
	ProtocolVersion string `json:"protocol_version" yaml:"protocol_version" mapstructure:"protocol_version"`

	// Server corresponds to the JSON schema field "server".
	Server PeerInfo `json:"server" yaml:"server" mapstructure:"server"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HelloSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["protocol_version"]; raw != nil && !ok {
		return fmt.Errorf("field protocol_version in HelloSchemaJsonResult: required")
	}
	if _, ok := raw["server"]; raw != nil && !ok {
		return fmt.Errorf("field server in HelloSchemaJsonResult: required")
	}
	type Plain HelloSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.ProtocolVersion != "1" {
		return fmt.Errorf("field %s: must be equal to %s", "protocol_version", "1")
	}
	*j = HelloSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HelloSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in HelloSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in HelloSchemaJson: required")
	}
	type Plain HelloSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = HelloSchemaJson(plain)
	return nil
}

// Reads an ExportedProfile document from 'path' on the daemon host's filesystem,
// validates it, and creates a new profile from it. The server generates a fresh
// id; any id in the file is ignored. Does not change the active profile. Returns
// the created profile.
type ImportProfileSchemaJson struct {
	// Params corresponds to the JSON schema field "params".
	Params ImportProfileSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result ImportProfileSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

type ImportProfileSchemaJsonParams struct {
	// Filesystem path on the daemon host of the exported file to import.
	Path string `json:"path" yaml:"path" mapstructure:"path"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ImportProfileSchemaJsonParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in ImportProfileSchemaJsonParams: required")
	}
	type Plain ImportProfileSchemaJsonParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Path)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "path", 1)
	}
	*j = ImportProfileSchemaJsonParams(plain)
	return nil
}

type ImportProfileSchemaJsonResult struct {
	// Profile corresponds to the JSON schema field "profile".
	Profile Profile `json:"profile" yaml:"profile" mapstructure:"profile"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ImportProfileSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["profile"]; raw != nil && !ok {
		return fmt.Errorf("field profile in ImportProfileSchemaJsonResult: required")
	}
	type Plain ImportProfileSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ImportProfileSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ImportProfileSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in ImportProfileSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in ImportProfileSchemaJson: required")
	}
	type Plain ImportProfileSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ImportProfileSchemaJson(plain)
	return nil
}

// A single physical input exposed by a device (a key or an encoder).
type Input struct {
	// Logical identifier of the input within the device (e.g. 'key_0x04',
	// 'encoder_0'). Matches InputEvent.input_id and Binding.input_id.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind InputKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Human-friendly label for the input (e.g. 'Key 1', 'Encoder'). Optional; clients
	// fall back to id.
	Label *string `json:"label,omitempty,omitzero" yaml:"label,omitempty" mapstructure:"label,omitempty"`
}

type InputAction string

const InputActionClick InputAction = "click"
const InputActionPress InputAction = "press"
const InputActionRelease InputAction = "release"
const InputActionRotateCcw InputAction = "rotate_ccw"
const InputActionRotateCw InputAction = "rotate_cw"

var enumValues_InputAction = []interface{}{
	"press",
	"release",
	"rotate_cw",
	"rotate_ccw",
	"click",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InputAction) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InputAction {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InputAction, v)
	}
	*j = InputAction(v)
	return nil
}

// A single hardware event coming from a HID device.
type InputEvent struct {
	// Action corresponds to the JSON schema field "action".
	Action InputAction `json:"action" yaml:"action" mapstructure:"action"`

	// DeviceId corresponds to the JSON schema field "device_id".
	DeviceId DeviceID `json:"device_id" yaml:"device_id" mapstructure:"device_id"`

	// Logical identifier of the input within the device (e.g. 'key_0x04',
	// 'encoder_0'). Matches Device.inputs[].id.
	InputId string `json:"input_id" yaml:"input_id" mapstructure:"input_id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind InputKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Unix epoch in milliseconds when the event was captured by the daemon.
	TimestampMs int `json:"timestamp_ms" yaml:"timestamp_ms" mapstructure:"timestamp_ms"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InputEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in InputEvent: required")
	}
	if _, ok := raw["device_id"]; raw != nil && !ok {
		return fmt.Errorf("field device_id in InputEvent: required")
	}
	if _, ok := raw["input_id"]; raw != nil && !ok {
		return fmt.Errorf("field input_id in InputEvent: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in InputEvent: required")
	}
	if _, ok := raw["timestamp_ms"]; raw != nil && !ok {
		return fmt.Errorf("field timestamp_ms in InputEvent: required")
	}
	type Plain InputEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.InputId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "input_id", 1)
	}
	if 0 > plain.TimestampMs {
		return fmt.Errorf("field %s: must be >= %v", "timestamp_ms", 0)
	}
	*j = InputEvent(plain)
	return nil
}

type InputKind string

const InputKindEncoder InputKind = "encoder"
const InputKindKey InputKind = "key"

var enumValues_InputKind = []interface{}{
	"key",
	"encoder",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InputKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InputKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InputKind, v)
	}
	*j = InputKind(v)
	return nil
}

// Pushed by the daemon for every hardware event captured on a connected HID
// device. High-frequency: encoders may emit many per second.
type InputSchemaJson struct {
	// Data corresponds to the JSON schema field "data".
	Data InputEvent `json:"data" yaml:"data" mapstructure:"data"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InputSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in InputSchemaJson: required")
	}
	type Plain InputSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = InputSchemaJson(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Input) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Input: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in Input: required")
	}
	type Plain Input
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if plain.Label != nil && utf8.RuneCountInString(string(*plain.Label)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "label", 1)
	}
	*j = Input(plain)
	return nil
}

// Params for the built-in 'launch_app' action: launches an application.
type LaunchAppActionParams struct {
	// Absolute path to the application or executable to launch.
	Path string `json:"path" yaml:"path" mapstructure:"path"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LaunchAppActionParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in LaunchAppActionParams: required")
	}
	type Plain LaunchAppActionParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Path)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "path", 1)
	}
	*j = LaunchAppActionParams(plain)
	return nil
}

// Returns the catalog of actions the daemon can bind to inputs, including the
// param shape each action needs so a client can render a config form. No params in
// v1.
type ListActionsSchemaJson struct {
	// No parameters in v1.
	Params ListActionsSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result ListActionsSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

// No parameters in v1.
type ListActionsSchemaJsonParams map[string]interface{}

type ListActionsSchemaJsonResult struct {
	// All actions available to bind. Built-ins plus any registered plugin actions.
	Actions []ActionDescriptor `json:"actions" yaml:"actions" mapstructure:"actions"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ListActionsSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["actions"]; raw != nil && !ok {
		return fmt.Errorf("field actions in ListActionsSchemaJsonResult: required")
	}
	type Plain ListActionsSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListActionsSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ListActionsSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in ListActionsSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in ListActionsSchemaJson: required")
	}
	type Plain ListActionsSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListActionsSchemaJson(plain)
	return nil
}

// Returns all bindings the daemon currently has configured. Read-side counterpart
// of set_binding. No filters in v1; clients filter client-side if needed.
type ListBindingsSchemaJson struct {
	// No parameters in v1.
	Params ListBindingsSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result ListBindingsSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

// No parameters in v1.
type ListBindingsSchemaJsonParams map[string]interface{}

type ListBindingsSchemaJsonResult struct {
	// All currently configured bindings.
	Bindings []Binding `json:"bindings" yaml:"bindings" mapstructure:"bindings"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ListBindingsSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bindings"]; raw != nil && !ok {
		return fmt.Errorf("field bindings in ListBindingsSchemaJsonResult: required")
	}
	type Plain ListBindingsSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListBindingsSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ListBindingsSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in ListBindingsSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in ListBindingsSchemaJson: required")
	}
	type Plain ListBindingsSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListBindingsSchemaJson(plain)
	return nil
}

// Returns the HID devices currently known to the daemon. No filters in v1; clients
// filter client-side if needed.
type ListDevicesSchemaJson struct {
	// No parameters in v1.
	Params ListDevicesSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result ListDevicesSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

// No parameters in v1.
type ListDevicesSchemaJsonParams map[string]interface{}

type ListDevicesSchemaJsonResult struct {
	// All currently enumerated HID devices.
	Devices []Device `json:"devices" yaml:"devices" mapstructure:"devices"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ListDevicesSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["devices"]; raw != nil && !ok {
		return fmt.Errorf("field devices in ListDevicesSchemaJsonResult: required")
	}
	type Plain ListDevicesSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListDevicesSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ListDevicesSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in ListDevicesSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in ListDevicesSchemaJson: required")
	}
	type Plain ListDevicesSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListDevicesSchemaJson(plain)
	return nil
}

// Returns all profiles the daemon currently has, along with the id of the active
// one. The active profile id is tracked at the daemon level and only exposed here.
type ListProfilesSchemaJson struct {
	// No parameters in v1.
	Params ListProfilesSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result ListProfilesSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

// No parameters in v1.
type ListProfilesSchemaJsonParams map[string]interface{}

type ListProfilesSchemaJsonResult struct {
	// Identifier of the currently active profile. Always references one of the
	// profiles in the array.
	ActiveProfileId string `json:"active_profile_id" yaml:"active_profile_id" mapstructure:"active_profile_id"`

	// All profiles known to the daemon.
	Profiles []Profile `json:"profiles" yaml:"profiles" mapstructure:"profiles"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ListProfilesSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["active_profile_id"]; raw != nil && !ok {
		return fmt.Errorf("field active_profile_id in ListProfilesSchemaJsonResult: required")
	}
	if _, ok := raw["profiles"]; raw != nil && !ok {
		return fmt.Errorf("field profiles in ListProfilesSchemaJsonResult: required")
	}
	type Plain ListProfilesSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.ActiveProfileId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "active_profile_id", 1)
	}
	*j = ListProfilesSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ListProfilesSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in ListProfilesSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in ListProfilesSchemaJson: required")
	}
	type Plain ListProfilesSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListProfilesSchemaJson(plain)
	return nil
}

// Params for the built-in 'macro' action: runs a sequence of actions in order. The
// schema allows any Action as a step; the daemon rejects nested macros (a step
// whose type is 'macro').
type MacroActionParams struct {
	// Actions to run in order. Must contain at least one step.
	Steps []Action `json:"steps" yaml:"steps" mapstructure:"steps"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MacroActionParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["steps"]; raw != nil && !ok {
		return fmt.Errorf("field steps in MacroActionParams: required")
	}
	type Plain MacroActionParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Steps != nil && len(plain.Steps) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "steps", 1)
	}
	*j = MacroActionParams(plain)
	return nil
}

// Describes one action parameter so a client can render an input for it.
type ParamSpec struct {
	// Human-friendly field label.
	Label string `json:"label" yaml:"label" mapstructure:"label"`

	// Param key written into Action.params.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Optional placeholder/example shown in the input.
	Placeholder *string `json:"placeholder,omitempty,omitzero" yaml:"placeholder,omitempty" mapstructure:"placeholder,omitempty"`

	// Required corresponds to the JSON schema field "required".
	Required bool `json:"required" yaml:"required" mapstructure:"required"`

	// Param value type. Only 'string' in v1.
	Type ParamSpecType `json:"type" yaml:"type" mapstructure:"type"`
}

type ParamSpecType string

const ParamSpecTypeString ParamSpecType = "string"

var enumValues_ParamSpecType = []interface{}{
	"string",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ParamSpecType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ParamSpecType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ParamSpecType, v)
	}
	*j = ParamSpecType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ParamSpec) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in ParamSpec: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ParamSpec: required")
	}
	if _, ok := raw["required"]; raw != nil && !ok {
		return fmt.Errorf("field required in ParamSpec: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ParamSpec: required")
	}
	type Plain ParamSpec
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Label)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "label", 1)
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	*j = ParamSpec(plain)
	return nil
}

// Self-identification of a protocol peer (client or server).
type PeerInfo struct {
	// Stable identifier of the peer implementation.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Semver version of the peer build.
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PeerInfo) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in PeerInfo: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in PeerInfo: required")
	}
	type Plain PeerInfo
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if utf8.RuneCountInString(string(plain.Version)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "version", 1)
	}
	*j = PeerInfo(plain)
	return nil
}

// A named set of bindings. The daemon keeps exactly one profile active at a time;
// switching profiles swaps the active binding set.
type Profile struct {
	// Bindings that belong to this profile.
	Bindings []Binding `json:"bindings" yaml:"bindings" mapstructure:"bindings"`

	// Stable server-generated identifier for the profile.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Human-friendly profile name.
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Profile) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bindings"]; raw != nil && !ok {
		return fmt.Errorf("field bindings in Profile: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Profile: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Profile: required")
	}
	type Plain Profile
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	*j = Profile(plain)
	return nil
}

// Renames an existing profile. Does not affect its bindings or the active profile.
type RenameProfileSchemaJson struct {
	// Params corresponds to the JSON schema field "params".
	Params RenameProfileSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Empty acknowledgement object. Reserved for future fields without breaking the
	// schema.
	Result RenameProfileSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

type RenameProfileSchemaJsonParams struct {
	// Identifier of the profile to rename.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// New human-friendly name for the profile.
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RenameProfileSchemaJsonParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in RenameProfileSchemaJsonParams: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in RenameProfileSchemaJsonParams: required")
	}
	type Plain RenameProfileSchemaJsonParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	*j = RenameProfileSchemaJsonParams(plain)
	return nil
}

// Empty acknowledgement object. Reserved for future fields without breaking the
// schema.
type RenameProfileSchemaJsonResult map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RenameProfileSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in RenameProfileSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in RenameProfileSchemaJson: required")
	}
	type Plain RenameProfileSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = RenameProfileSchemaJson(plain)
	return nil
}

// Client -> server. Expects a correlated Response with the same id.
type Request struct {
	// Client-generated correlation id (UUID v4 or nanoid).
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Method name in snake_case.
	Method string `json:"method" yaml:"method" mapstructure:"method"`

	// Method-specific arguments. Refined by the schema in
	// schemas/methods/<method>.schema.json.
	Params RequestParams `json:"params" yaml:"params" mapstructure:"params"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// Method-specific arguments. Refined by the schema in
// schemas/methods/<method>.schema.json.
type RequestParams map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Request) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Request: required")
	}
	if _, ok := raw["method"]; raw != nil && !ok {
		return fmt.Errorf("field method in Request: required")
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in Request: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Request: required")
	}
	type Plain Request
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9_]*$`, string(plain.Method)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Method", `^[a-z][a-z0-9_]*$`)
	}
	*j = Request(plain)
	return nil
}

// Server -> client. Discriminated by 'ok'.
type Response map[string]interface{}

type ResponseErr struct {
	// Error corresponds to the JSON schema field "error".
	Error Error `json:"error" yaml:"error" mapstructure:"error"`

	// Echo of the original Request.id.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Ok corresponds to the JSON schema field "ok".
	Ok interface{} `json:"ok" yaml:"ok" mapstructure:"ok"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResponseErr) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["error"]; raw != nil && !ok {
		return fmt.Errorf("field error in ResponseErr: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ResponseErr: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in ResponseErr: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ResponseErr: required")
	}
	type Plain ResponseErr
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = ResponseErr(plain)
	return nil
}

type ResponseOk struct {
	// Method-specific result. Refined by the schema in
	// schemas/methods/<method>.schema.json.
	Data ResponseOkData `json:"data" yaml:"data" mapstructure:"data"`

	// Echo of the original Request.id.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Ok corresponds to the JSON schema field "ok".
	Ok interface{} `json:"ok" yaml:"ok" mapstructure:"ok"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// Method-specific result. Refined by the schema in
// schemas/methods/<method>.schema.json.
type ResponseOkData map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResponseOk) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in ResponseOk: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ResponseOk: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in ResponseOk: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ResponseOk: required")
	}
	type Plain ResponseOk
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = ResponseOk(plain)
	return nil
}

// Params for the built-in 'send_keys' action: types a key combination.
type SendKeysActionParams struct {
	// Key combination to send, e.g. 'Ctrl+Shift+S'.
	Keys string `json:"keys" yaml:"keys" mapstructure:"keys"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SendKeysActionParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["keys"]; raw != nil && !ok {
		return fmt.Errorf("field keys in SendKeysActionParams: required")
	}
	type Plain SendKeysActionParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Keys)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "keys", 1)
	}
	*j = SendKeysActionParams(plain)
	return nil
}

// Sets which profile is active. The active profile is the one the binding editor
// reads and writes; switching it swaps the live binding set.
type SetActiveProfileSchemaJson struct {
	// Params corresponds to the JSON schema field "params".
	Params SetActiveProfileSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result SetActiveProfileSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

type SetActiveProfileSchemaJsonParams struct {
	// Identifier of the profile to activate.
	Id string `json:"id" yaml:"id" mapstructure:"id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetActiveProfileSchemaJsonParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in SetActiveProfileSchemaJsonParams: required")
	}
	type Plain SetActiveProfileSchemaJsonParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = SetActiveProfileSchemaJsonParams(plain)
	return nil
}

type SetActiveProfileSchemaJsonResult struct {
	// Identifier of the now-active profile. Echoes the requested id on success.
	ActiveProfileId string `json:"active_profile_id" yaml:"active_profile_id" mapstructure:"active_profile_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetActiveProfileSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["active_profile_id"]; raw != nil && !ok {
		return fmt.Errorf("field active_profile_id in SetActiveProfileSchemaJsonResult: required")
	}
	type Plain SetActiveProfileSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.ActiveProfileId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "active_profile_id", 1)
	}
	*j = SetActiveProfileSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetActiveProfileSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in SetActiveProfileSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in SetActiveProfileSchemaJson: required")
	}
	type Plain SetActiveProfileSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SetActiveProfileSchemaJson(plain)
	return nil
}

// Replaces the entire auto-switch configuration in one shot (bulk set, not
// per-rule CRUD): the master toggle and the full rule set. The result echoes the
// persisted state.
type SetAutoSwitchSchemaJson struct {
	// Params corresponds to the JSON schema field "params".
	Params SetAutoSwitchSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result SetAutoSwitchSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

type SetAutoSwitchSchemaJsonParams struct {
	// Master toggle. When false, the daemon ignores the rules and never
	// auto-switches.
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`

	// Full replacement set of app-to-profile rules. Any previously stored rules are
	// discarded.
	Rules []AutoSwitchRule `json:"rules" yaml:"rules" mapstructure:"rules"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetAutoSwitchSchemaJsonParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["enabled"]; raw != nil && !ok {
		return fmt.Errorf("field enabled in SetAutoSwitchSchemaJsonParams: required")
	}
	if _, ok := raw["rules"]; raw != nil && !ok {
		return fmt.Errorf("field rules in SetAutoSwitchSchemaJsonParams: required")
	}
	type Plain SetAutoSwitchSchemaJsonParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SetAutoSwitchSchemaJsonParams(plain)
	return nil
}

type SetAutoSwitchSchemaJsonResult struct {
	// Master toggle as persisted. Echoes the requested value on success.
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`

	// Rules as persisted. Echoes the requested set on success.
	Rules []AutoSwitchRule `json:"rules" yaml:"rules" mapstructure:"rules"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetAutoSwitchSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["enabled"]; raw != nil && !ok {
		return fmt.Errorf("field enabled in SetAutoSwitchSchemaJsonResult: required")
	}
	if _, ok := raw["rules"]; raw != nil && !ok {
		return fmt.Errorf("field rules in SetAutoSwitchSchemaJsonResult: required")
	}
	type Plain SetAutoSwitchSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SetAutoSwitchSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetAutoSwitchSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in SetAutoSwitchSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in SetAutoSwitchSchemaJson: required")
	}
	type Plain SetAutoSwitchSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SetAutoSwitchSchemaJson(plain)
	return nil
}

// Creates or updates a binding (input -> action) on a device. The pair (device_id,
// input_id, trigger) is the unique key; calling this method with an existing key
// replaces the previous action.
type SetBindingSchemaJson struct {
	// Params corresponds to the JSON schema field "params".
	Params SetBindingSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Empty acknowledgement object. Reserved for future fields (e.g. server-assigned
	// binding id) without breaking the schema.
	Result SetBindingSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

type SetBindingSchemaJsonParams struct {
	// Binding corresponds to the JSON schema field "binding".
	Binding Binding `json:"binding" yaml:"binding" mapstructure:"binding"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetBindingSchemaJsonParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["binding"]; raw != nil && !ok {
		return fmt.Errorf("field binding in SetBindingSchemaJsonParams: required")
	}
	type Plain SetBindingSchemaJsonParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SetBindingSchemaJsonParams(plain)
	return nil
}

// Empty acknowledgement object. Reserved for future fields (e.g. server-assigned
// binding id) without breaking the schema.
type SetBindingSchemaJsonResult map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetBindingSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in SetBindingSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in SetBindingSchemaJson: required")
	}
	type Plain SetBindingSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SetBindingSchemaJson(plain)
	return nil
}
