// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package protocol

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "unicode/utf8"

// An executable action bound to an input.
type Action struct {
	// Action-specific parameters. Schema depends on 'type'.
	Params ActionParams `json:"params,omitempty,omitzero" yaml:"params,omitempty" mapstructure:"params,omitempty"`

	// Action type. Built-ins are well-known; plugin actions use
	// 'plugin.<plugin_id>.<action_id>'.
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// Action-specific parameters. Schema depends on 'type'.
type ActionParams map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Action) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Action: required")
	}
	type Plain Action
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Action(plain)
	return nil
}

// Maps an input on a specific device to an action.
type Binding struct {
	// Action corresponds to the JSON schema field "action".
	Action Action `json:"action" yaml:"action" mapstructure:"action"`

	// DeviceId corresponds to the JSON schema field "device_id".
	DeviceId DeviceID `json:"device_id" yaml:"device_id" mapstructure:"device_id"`

	// InputId corresponds to the JSON schema field "input_id".
	InputId string `json:"input_id" yaml:"input_id" mapstructure:"input_id"`

	// Trigger corresponds to the JSON schema field "trigger".
	Trigger InputAction `json:"trigger" yaml:"trigger" mapstructure:"trigger"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Binding) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in Binding: required")
	}
	if _, ok := raw["device_id"]; raw != nil && !ok {
		return fmt.Errorf("field device_id in Binding: required")
	}
	if _, ok := raw["input_id"]; raw != nil && !ok {
		return fmt.Errorf("field input_id in Binding: required")
	}
	if _, ok := raw["trigger"]; raw != nil && !ok {
		return fmt.Errorf("field trigger in Binding: required")
	}
	type Plain Binding
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.InputId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "input_id", 1)
	}
	*j = Binding(plain)
	return nil
}

// A HID device known to the daemon. Returned by list_devices.
type Device struct {
	// Id corresponds to the JSON schema field "id".
	Id DeviceID `json:"id" yaml:"id" mapstructure:"id"`

	// Manufacturer string from the HID descriptor. May be missing on cheap/clone
	// devices.
	Manufacturer *string `json:"manufacturer,omitempty,omitzero" yaml:"manufacturer,omitempty" mapstructure:"manufacturer,omitempty"`

	// OS-opaque path used by the HID library to (re)open the device. Format varies
	// per OS; clients should treat it as an opaque token.
	Path string `json:"path" yaml:"path" mapstructure:"path"`

	// Product name string from the HID descriptor.
	Product *string `json:"product,omitempty,omitzero" yaml:"product,omitempty" mapstructure:"product,omitempty"`

	// USB Product ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x'
	// prefix).
	ProductId string `json:"product_id" yaml:"product_id" mapstructure:"product_id"`

	// Serial number string from the HID descriptor. Not all HID devices expose one.
	SerialNumber *string `json:"serial_number,omitempty,omitzero" yaml:"serial_number,omitempty" mapstructure:"serial_number,omitempty"`

	// USB Vendor ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x'
	// prefix).
	VendorId string `json:"vendor_id" yaml:"vendor_id" mapstructure:"vendor_id"`
}

// Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
type DeviceID string

// UnmarshalJSON implements json.Unmarshaler.
func (j *DeviceID) UnmarshalJSON(value []byte) error {
	type Plain DeviceID
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^VID_[0-9A-Fa-f]{4}_PID_[0-9A-Fa-f]{4}(_.+)?$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^VID_[0-9A-Fa-f]{4}_PID_[0-9A-Fa-f]{4}(_.+)?$`)
	}
	*j = DeviceID(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Device) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Device: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in Device: required")
	}
	if _, ok := raw["product_id"]; raw != nil && !ok {
		return fmt.Errorf("field product_id in Device: required")
	}
	if _, ok := raw["vendor_id"]; raw != nil && !ok {
		return fmt.Errorf("field vendor_id in Device: required")
	}
	type Plain Device
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Path)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "path", 1)
	}
	if matched, _ := regexp.MatchString(`^[0-9A-Fa-f]{4}$`, string(plain.ProductId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ProductId", `^[0-9A-Fa-f]{4}$`)
	}
	if matched, _ := regexp.MatchString(`^[0-9A-Fa-f]{4}$`, string(plain.VendorId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "VendorId", `^[0-9A-Fa-f]{4}$`)
	}
	*j = Device(plain)
	return nil
}

// Failure payload returned in a Response with ok=false.
type Error struct {
	// Stable, machine-readable error code in SCREAMING_SNAKE_CASE.
	Code string `json:"code" yaml:"code" mapstructure:"code"`

	// Optional structured context for debugging.
	Details ErrorDetails `json:"details,omitempty,omitzero" yaml:"details,omitempty" mapstructure:"details,omitempty"`

	// Human-readable error message. Free form, may be localized in future versions.
	Message string `json:"message" yaml:"message" mapstructure:"message"`
}

// Optional structured context for debugging.
type ErrorDetails map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Error) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["code"]; raw != nil && !ok {
		return fmt.Errorf("field code in Error: required")
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in Error: required")
	}
	type Plain Error
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Z][A-Z0-9_]*$`, string(plain.Code)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Code", `^[A-Z][A-Z0-9_]*$`)
	}
	if utf8.RuneCountInString(string(plain.Message)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "message", 1)
	}
	*j = Error(plain)
	return nil
}

// Server -> client, no correlation. Stream of hardware events or daemon
// notifications.
type Event struct {
	// Event-specific payload. Refined by the schema in
	// schemas/events/<name>.schema.json.
	Data EventData `json:"data" yaml:"data" mapstructure:"data"`

	// Event name in snake_case.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// Event-specific payload. Refined by the schema in
// schemas/events/<name>.schema.json.
type EventData map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Event) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in Event: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Event: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Event: required")
	}
	type Plain Event
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9_]*$`, string(plain.Name)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Name", `^[a-z][a-z0-9_]*$`)
	}
	*j = Event(plain)
	return nil
}

// Mandatory first request after a WebSocket connection is established. The client
// declares the protocol_version it speaks. The server either accepts
// (Response.ok=true with its own identification) or closes the connection with an
// UNSUPPORTED_PROTOCOL_VERSION error. After a successful hello no further version
// negotiation happens; the contract is fixed for the session.
type HelloSchemaJson struct {
	// Params corresponds to the JSON schema field "params".
	Params HelloSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result HelloSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

type HelloSchemaJsonParams struct {
	// Client corresponds to the JSON schema field "client".
	Client PeerInfo `json:"client" yaml:"client" mapstructure:"client"`

	// Major version of the protocol the client implements. Currently '1'.
	ProtocolVersion string `json:"protocol_version" yaml:"protocol_version" mapstructure:"protocol_version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HelloSchemaJsonParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["client"]; raw != nil && !ok {
		return fmt.Errorf("field client in HelloSchemaJsonParams: required")
	}
	if _, ok := raw["protocol_version"]; raw != nil && !ok {
		return fmt.Errorf("field protocol_version in HelloSchemaJsonParams: required")
	}
	type Plain HelloSchemaJsonParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.ProtocolVersion != "1" {
		return fmt.Errorf("field %s: must be equal to %s", "protocol_version", "1")
	}
	*j = HelloSchemaJsonParams(plain)
	return nil
}

type HelloSchemaJsonResult struct {
	// Protocol version the server agrees to speak for this session.
	ProtocolVersion string `json:"protocol_version" yaml:"protocol_version" mapstructure:"protocol_version"`

	// Server corresponds to the JSON schema field "server".
	Server PeerInfo `json:"server" yaml:"server" mapstructure:"server"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HelloSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["protocol_version"]; raw != nil && !ok {
		return fmt.Errorf("field protocol_version in HelloSchemaJsonResult: required")
	}
	if _, ok := raw["server"]; raw != nil && !ok {
		return fmt.Errorf("field server in HelloSchemaJsonResult: required")
	}
	type Plain HelloSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.ProtocolVersion != "1" {
		return fmt.Errorf("field %s: must be equal to %s", "protocol_version", "1")
	}
	*j = HelloSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HelloSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in HelloSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in HelloSchemaJson: required")
	}
	type Plain HelloSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = HelloSchemaJson(plain)
	return nil
}

type InputAction string

const InputActionClick InputAction = "click"
const InputActionPress InputAction = "press"
const InputActionRelease InputAction = "release"
const InputActionRotateCcw InputAction = "rotate_ccw"
const InputActionRotateCw InputAction = "rotate_cw"

var enumValues_InputAction = []interface{}{
	"press",
	"release",
	"rotate_cw",
	"rotate_ccw",
	"click",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InputAction) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InputAction {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InputAction, v)
	}
	*j = InputAction(v)
	return nil
}

// A single hardware event coming from a HID device.
type InputEvent struct {
	// Action corresponds to the JSON schema field "action".
	Action InputAction `json:"action" yaml:"action" mapstructure:"action"`

	// DeviceId corresponds to the JSON schema field "device_id".
	DeviceId DeviceID `json:"device_id" yaml:"device_id" mapstructure:"device_id"`

	// Logical identifier of the input within the device (e.g. 'K1', 'ENC1').
	InputId string `json:"input_id" yaml:"input_id" mapstructure:"input_id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind InputKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Unix epoch in milliseconds when the event was captured by the daemon.
	TimestampMs int `json:"timestamp_ms" yaml:"timestamp_ms" mapstructure:"timestamp_ms"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InputEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in InputEvent: required")
	}
	if _, ok := raw["device_id"]; raw != nil && !ok {
		return fmt.Errorf("field device_id in InputEvent: required")
	}
	if _, ok := raw["input_id"]; raw != nil && !ok {
		return fmt.Errorf("field input_id in InputEvent: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in InputEvent: required")
	}
	if _, ok := raw["timestamp_ms"]; raw != nil && !ok {
		return fmt.Errorf("field timestamp_ms in InputEvent: required")
	}
	type Plain InputEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.InputId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "input_id", 1)
	}
	if 0 > plain.TimestampMs {
		return fmt.Errorf("field %s: must be >= %v", "timestamp_ms", 0)
	}
	*j = InputEvent(plain)
	return nil
}

type InputKind string

const InputKindEncoder InputKind = "encoder"
const InputKindKey InputKind = "key"

var enumValues_InputKind = []interface{}{
	"key",
	"encoder",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InputKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InputKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InputKind, v)
	}
	*j = InputKind(v)
	return nil
}

// Pushed by the daemon for every hardware event captured on a connected HID
// device. High-frequency: encoders may emit many per second.
type InputSchemaJson struct {
	// Data corresponds to the JSON schema field "data".
	Data InputEvent `json:"data" yaml:"data" mapstructure:"data"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InputSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in InputSchemaJson: required")
	}
	type Plain InputSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = InputSchemaJson(plain)
	return nil
}

// Returns the HID devices currently known to the daemon. No filters in v1; clients
// filter client-side if needed.
type ListDevicesSchemaJson struct {
	// No parameters in v1.
	Params ListDevicesSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Result corresponds to the JSON schema field "result".
	Result ListDevicesSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

// No parameters in v1.
type ListDevicesSchemaJsonParams map[string]interface{}

type ListDevicesSchemaJsonResult struct {
	// All currently enumerated HID devices.
	Devices []Device `json:"devices" yaml:"devices" mapstructure:"devices"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ListDevicesSchemaJsonResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["devices"]; raw != nil && !ok {
		return fmt.Errorf("field devices in ListDevicesSchemaJsonResult: required")
	}
	type Plain ListDevicesSchemaJsonResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListDevicesSchemaJsonResult(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ListDevicesSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in ListDevicesSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in ListDevicesSchemaJson: required")
	}
	type Plain ListDevicesSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListDevicesSchemaJson(plain)
	return nil
}

// Self-identification of a protocol peer (client or server).
type PeerInfo struct {
	// Stable identifier of the peer implementation.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Semver version of the peer build.
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PeerInfo) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in PeerInfo: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in PeerInfo: required")
	}
	type Plain PeerInfo
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if utf8.RuneCountInString(string(plain.Version)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "version", 1)
	}
	*j = PeerInfo(plain)
	return nil
}

// Client -> server. Expects a correlated Response with the same id.
type Request struct {
	// Client-generated correlation id (UUID v4 or nanoid).
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Method name in snake_case.
	Method string `json:"method" yaml:"method" mapstructure:"method"`

	// Method-specific arguments. Refined by the schema in
	// schemas/methods/<method>.schema.json.
	Params RequestParams `json:"params" yaml:"params" mapstructure:"params"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// Method-specific arguments. Refined by the schema in
// schemas/methods/<method>.schema.json.
type RequestParams map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Request) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Request: required")
	}
	if _, ok := raw["method"]; raw != nil && !ok {
		return fmt.Errorf("field method in Request: required")
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in Request: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Request: required")
	}
	type Plain Request
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9_]*$`, string(plain.Method)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Method", `^[a-z][a-z0-9_]*$`)
	}
	*j = Request(plain)
	return nil
}

// Server -> client. Discriminated by 'ok'.
type Response map[string]interface{}

type ResponseErr struct {
	// Error corresponds to the JSON schema field "error".
	Error Error `json:"error" yaml:"error" mapstructure:"error"`

	// Echo of the original Request.id.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Ok corresponds to the JSON schema field "ok".
	Ok interface{} `json:"ok" yaml:"ok" mapstructure:"ok"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResponseErr) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["error"]; raw != nil && !ok {
		return fmt.Errorf("field error in ResponseErr: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ResponseErr: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in ResponseErr: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ResponseErr: required")
	}
	type Plain ResponseErr
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = ResponseErr(plain)
	return nil
}

type ResponseOk struct {
	// Method-specific result. Refined by the schema in
	// schemas/methods/<method>.schema.json.
	Data ResponseOkData `json:"data" yaml:"data" mapstructure:"data"`

	// Echo of the original Request.id.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Ok corresponds to the JSON schema field "ok".
	Ok interface{} `json:"ok" yaml:"ok" mapstructure:"ok"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// Method-specific result. Refined by the schema in
// schemas/methods/<method>.schema.json.
type ResponseOkData map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResponseOk) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in ResponseOk: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ResponseOk: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in ResponseOk: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ResponseOk: required")
	}
	type Plain ResponseOk
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = ResponseOk(plain)
	return nil
}

// Creates or updates a binding (input -> action) on a device. The pair (device_id,
// input_id, trigger) is the unique key; calling this method with an existing key
// replaces the previous action.
type SetBindingSchemaJson struct {
	// Params corresponds to the JSON schema field "params".
	Params SetBindingSchemaJsonParams `json:"params" yaml:"params" mapstructure:"params"`

	// Empty acknowledgement object. Reserved for future fields (e.g. server-assigned
	// binding id) without breaking the schema.
	Result SetBindingSchemaJsonResult `json:"result" yaml:"result" mapstructure:"result"`
}

type SetBindingSchemaJsonParams struct {
	// Binding corresponds to the JSON schema field "binding".
	Binding Binding `json:"binding" yaml:"binding" mapstructure:"binding"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetBindingSchemaJsonParams) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["binding"]; raw != nil && !ok {
		return fmt.Errorf("field binding in SetBindingSchemaJsonParams: required")
	}
	type Plain SetBindingSchemaJsonParams
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SetBindingSchemaJsonParams(plain)
	return nil
}

// Empty acknowledgement object. Reserved for future fields (e.g. server-assigned
// binding id) without breaking the schema.
type SetBindingSchemaJsonResult map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetBindingSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["params"]; raw != nil && !ok {
		return fmt.Errorf("field params in SetBindingSchemaJson: required")
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in SetBindingSchemaJson: required")
	}
	type Plain SetBindingSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SetBindingSchemaJson(plain)
	return nil
}
