# generated by datamodel-codegen:
#   filename:  events/action_invoked.schema.json

from typing import NotRequired, TypedDict

from .. import common_schema
from .._json import JsonObject


class Action(TypedDict, closed=True):
    """
    The plugin action to run.
    """

    id: str
    """
    Action id as declared in the plugin manifest (PluginAction.id), without the 'plugin.<plugin_id>.' prefix.
    """
    params: JsonObject
    """
    Action.params from the binding, as configured by the user. Always present: {} when the binding has no params.
    """


class Data(TypedDict, closed=True):
    context: str
    """
    Opaque id of the binding instance that fired: unique per binding and per step of a macro or of each list of a toggle, and stable for as long as that binding exists (also across daemon restarts). Lets a plugin keep per-instance state, e.g. a toggle bound to two keys. Plugins must not parse it.
    """
    action: Action
    """
    The plugin action to run.
    """
    input: NotRequired[common_schema.InputEvent]
    """
    Hardware event that fired the binding (e.g. lets a plugin tell rotate_cw from rotate_ccw). Absent when the action was not fired by hardware (e.g. a test run from the GUI).
    """


class EventActionInvoked(TypedDict, closed=True):
    """
    Sent by the daemon to a single plugin connection (never broadcast) when a binding or macro step whose action is 'plugin.<plugin_id>.<action_id>' fires for that plugin. Fire-and-forget: the daemon does not wait for the plugin, so a failing plugin action cannot stop a macro it is part of.
    """

    data: Data
