# generated by datamodel-codegen:
#   filename:  events/active_profile_changed.schema.json

from typing import TypedDict


class Data(TypedDict, closed=True):
    active_profile_id: str
    """
    Identifier of the now-active profile.
    """


class EventActiveProfileChanged(TypedDict, closed=True):
    """
    Pushed by the daemon whenever the active profile changes on the server's own initiative (today: auto-switch by foreground app). Lets clients stay in sync without polling. Not emitted in response to a client's set_active_profile request, which already returns the new id.
    """

    data: Data
