# generated by datamodel-codegen:
#   filename:  events/input.schema.json

from typing import TypedDict

from .. import common_schema


class EventInput(TypedDict, closed=True):
    """
    Pushed by the daemon for every hardware event captured on a connected HID device. High-frequency: encoders may emit many per second.
    """

    data: common_schema.InputEvent
