/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
 */
export type DeviceID = string;
/**
 * Kind of physical input.
 */
export type InputKind = "key" | "encoder";
/**
 * What happened on the input.
 */
export type InputAction = "press" | "release" | "rotate_cw" | "rotate_ccw" | "click";

/**
 * Sent by the daemon to a single plugin connection (never broadcast) when a binding or macro step whose action is 'plugin.<plugin_id>.<action_id>' fires for that plugin. Fire-and-forget: the daemon does not wait for the plugin, so a failing plugin action cannot stop a macro it is part of.
 */
export interface EventActionInvoked {
  data: {
    /**
     * Opaque id of the binding instance that fired: unique per binding and per macro step, and stable for as long as that binding exists (also across daemon restarts). Lets a plugin keep per-instance state, e.g. a toggle bound to two keys. Plugins must not parse it.
     */
    context: string;
    /**
     * The plugin action to run.
     */
    action: {
      /**
       * Action id as declared in the plugin manifest (PluginAction.id), without the 'plugin.<plugin_id>.' prefix.
       */
      id: string;
      /**
       * Action.params from the binding, as configured by the user. Always present: {} when the binding has no params.
       */
      params: {
        [k: string]: unknown;
      };
    };
    input?: InputEvent;
  };
}
/**
 * Hardware event that fired the binding (e.g. lets a plugin tell rotate_cw from rotate_ccw). Absent when the action was not fired by hardware (e.g. a test run from the GUI).
 */
export interface InputEvent {
  device_id: DeviceID;
  kind: InputKind;
  /**
   * Logical identifier of the input within the device (e.g. 'key_0x04', 'encoder_0'). Matches Device.inputs[].id.
   */
  input_id: string;
  action: InputAction;
  /**
   * Unix epoch in milliseconds when the event was captured by the daemon.
   */
  timestamp_ms: number;
}
