/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
 */
export type DeviceID = string;
/**
 * Kind of physical input.
 */
export type InputKind = "key" | "encoder";
/**
 * What happened on the input.
 */
export type InputAction = "press" | "release" | "rotate_cw" | "rotate_ccw" | "click";

/**
 * Pushed by the daemon for every hardware event captured on a connected HID device. High-frequency: encoders may emit many per second.
 */
export interface EventInput {
  data: InputEvent;
}
/**
 * A single hardware event coming from a HID device.
 */
export interface InputEvent {
  device_id: DeviceID;
  kind: InputKind;
  /**
   * Logical identifier of the input within the device (e.g. 'key_0x04', 'encoder_0'). Matches Device.inputs[].id.
   */
  input_id: string;
  action: InputAction;
  /**
   * Unix epoch in milliseconds when the event was captured by the daemon.
   */
  timestamp_ms: number;
}
