/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "DeviceID".
 */
export type DeviceID = string;
/**
 * Kind of physical input.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "InputKind".
 */
export type InputKind = "key" | "encoder";
/**
 * What happened on the input.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "InputAction".
 */
export type InputAction = "press" | "release" | "rotate_cw" | "rotate_ccw" | "click";
/**
 * Globally unique plugin identifier in reverse-DNS form (e.g. 'dev.jonidg.spotify'). Lowercase, at least two dot-separated segments, each starting with a letter. Used as the install folder name and as <plugin_id> in Action.type.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "PluginID".
 */
export type PluginID = string;
/**
 * Id of the plugin being launched (its manifest id).
 */
export type PluginID1 = string;
/**
 * Globally unique reverse-DNS plugin id; install folder name and <plugin_id> in Action.type.
 */
export type PluginID2 = string;

/**
 * Shared type definitions referenced by message schemas.
 */
export interface CommonTypes {
  [k: string]: unknown;
}
/**
 * A single hardware event coming from a HID device.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "InputEvent".
 */
export interface InputEvent {
  device_id: DeviceID;
  kind: InputKind;
  /**
   * Logical identifier of the input within the device (e.g. 'key_0x04', 'encoder_0'). Matches Device.inputs[].id.
   */
  input_id: string;
  action: InputAction;
  /**
   * Unix epoch in milliseconds when the event was captured by the daemon.
   */
  timestamp_ms: number;
}
/**
 * An executable action bound to an input.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Action".
 */
export interface Action {
  /**
   * Action type. Built-ins are well-known; plugin actions use 'plugin.<plugin_id>.<action_id>'. Plugin ids are reverse-DNS (they contain dots) and action ids never do, so the action id is everything after the last dot.
   */
  type: string;
  /**
   * Action-specific parameters. Schema depends on 'type'. The daemon validates them against the per-type ActionParams definition (e.g. DelayActionParams for type 'delay').
   */
  params?: {
    [k: string]: unknown;
  };
}
/**
 * Params for the built-in 'send_keys' action: types a key combination.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "SendKeysActionParams".
 */
export interface SendKeysActionParams {
  /**
   * Key combination to send, e.g. 'Ctrl+Shift+S'.
   */
  keys: string;
}
/**
 * Params for the built-in 'launch_app' action: launches an application.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "LaunchAppActionParams".
 */
export interface LaunchAppActionParams {
  /**
   * Absolute path to the application or executable to launch.
   */
  path: string;
}
/**
 * Params for the built-in 'delay' action: waits for the given duration. Mainly useful as a step inside a macro.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "DelayActionParams".
 */
export interface DelayActionParams {
  /**
   * Milliseconds to wait before continuing.
   */
  ms: number;
}
/**
 * Params for the built-in 'macro' action: runs a sequence of actions in order. The schema allows any Action as a step; the daemon rejects nested macros (a step whose type is 'macro').
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "MacroActionParams".
 */
export interface MacroActionParams {
  /**
   * Actions to run in order. Must contain at least one step.
   *
   * @minItems 1
   */
  steps: [Action, ...Action[]];
}
/**
 * Maps an input on a specific device to an action.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Binding".
 */
export interface Binding {
  device_id: DeviceID;
  input_id: string;
  trigger: InputAction;
  action: Action;
}
/**
 * A named set of bindings. The daemon keeps exactly one profile active at a time; switching profiles swaps the active binding set.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Profile".
 */
export interface Profile {
  /**
   * Stable server-generated identifier for the profile.
   */
  id: string;
  /**
   * Human-friendly profile name.
   */
  name: string;
  /**
   * Bindings that belong to this profile.
   */
  bindings: Binding[];
}
/**
 * Portable, on-disk representation of a profile, written by export_profile and read by import_profile. Carries no server-local id: the id is meaningless outside the originating installation, so import always assigns a fresh one. The 'version' field lets readers detect and adapt to format changes.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "ExportedProfile".
 */
export interface ExportedProfile {
  /**
   * Magic marker identifying the file as a KeyForge profile export.
   */
  format: "keyforge.profile";
  /**
   * Export format version. Currently 1; bumped if the on-disk shape changes.
   */
  version: 1;
  /**
   * Human-friendly profile name.
   */
  name: string;
  /**
   * Bindings that belong to the exported profile.
   */
  bindings: Binding[];
}
/**
 * A single physical input exposed by a device (a key or an encoder).
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Input".
 */
export interface Input {
  /**
   * Logical identifier of the input within the device (e.g. 'key_0x04', 'encoder_0'). Matches InputEvent.input_id and Binding.input_id.
   */
  id: string;
  kind: InputKind;
  /**
   * Human-friendly label for the input (e.g. 'Key 1', 'Encoder'). Optional; clients fall back to id.
   */
  label?: string;
}
/**
 * A HID device known to the daemon. Returned by list_devices.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Device".
 */
export interface Device {
  id: DeviceID;
  /**
   * USB Vendor ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
   */
  vendor_id: string;
  /**
   * USB Product ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
   */
  product_id: string;
  /**
   * Manufacturer string from the HID descriptor. May be missing on cheap/clone devices.
   */
  manufacturer?: string;
  /**
   * Product name string from the HID descriptor.
   */
  product?: string;
  /**
   * Serial number string from the HID descriptor. Not all HID devices expose one.
   */
  serial_number?: string;
  /**
   * OS-opaque path used by the HID library to (re)open the device. Format varies per OS; clients should treat it as an opaque token.
   */
  path: string;
  /**
   * Inputs (keys/encoders) the daemon knows this device exposes. Empty for unrecognized devices the daemon can't map.
   */
  inputs: Input[];
}
/**
 * Maps a foreground application to the profile that should become active while that app is frontmost. When the frontmost app matches no rule, the active profile is left unchanged (sticky behavior); there is no fallback profile.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "AutoSwitchRule".
 */
export interface AutoSwitchRule {
  /**
   * OS-native application identifier: bundle id on macOS, executable name on Linux/Windows. Opaque string, not portable across OSes; the daemon matches it verbatim against the frontmost app.
   */
  app: string;
  /**
   * Identifier of the profile to activate when this app is frontmost.
   */
  profile_id: string;
}
/**
 * Describes one action parameter so a client can render an input for it.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "ParamSpec".
 */
export interface ParamSpec {
  /**
   * Param key written into Action.params. Unique within the action.
   */
  name: string;
  /**
   * Human-friendly field label.
   */
  label: string;
  /**
   * Param value type. Only 'string' in v1.
   */
  type: "string";
  required: boolean;
  /**
   * Optional placeholder/example shown in the input.
   */
  placeholder?: string;
}
/**
 * Connection info the daemon hands to a plugin process it spawns, serialized as JSON in the KEYFORGE_PLUGIN_INFO environment variable (an env var rather than CLI args, so the token is not visible in the process list). The plugin connects to ws_url, sends hello with client.name set to plugin_id, and must exit when that connection closes.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "PluginLaunchInfo".
 */
export interface PluginLaunchInfo {
  plugin_id: PluginID1;
  /**
   * WebSocket URL to connect to, including the per-plugin auth token as a query param. Treat it as a secret: the token identifies the plugin to the daemon and is distinct from the GUI's session token.
   */
  ws_url: string;
  /**
   * Protocol major version the daemon speaks. The plugin sends it back in hello. Currently '1'.
   */
  protocol_version: "1";
}
/**
 * Contents of the manifest.json file at the root of a plugin. A plugin is distributed as a '.keyforgeplugin' file: a zip archive with manifest.json at its root (no wrapping folder) plus every file the manifest references. The daemon installs it by extracting the archive into '<config dir>/plugins/<id>/', taking the id from the manifest. All file paths in the manifest (icon, and entrypoint paths containing '/') are relative to the plugin root, use '/' as separator, and must stay inside the plugin root: the daemon rejects '..' segments and any path or archive entry that escapes the root.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "PluginManifest".
 */
export interface PluginManifest {
  /**
   * Manifest format version. Currently 1; bumped if the manifest shape changes.
   */
  manifest_version: 1;
  id: PluginID2;
  /**
   * Human-friendly plugin name for the UI.
   */
  name: string;
  /**
   * Plugin version (SemVer 2.0).
   */
  version: string;
  /**
   * Major version of the protocol the plugin speaks. Lets the daemon reject an incompatible plugin before spawning it. Currently '1'.
   */
  protocol_version: "1";
  /**
   * Plugin author, shown in the UI.
   */
  author?: string;
  /**
   * Short description of what the plugin does.
   */
  description?: string;
  /**
   * URL of the plugin homepage or source repository.
   */
  homepage?: string;
  /**
   * Category the UI groups the plugin's actions under (e.g. 'Audio', 'Streaming').
   */
  category?: string;
  /**
   * Path to the plugin icon, relative to the plugin root. No leading '/', no '\' and no ':'.
   */
  icon?: string;
  /**
   * Command the daemon runs to start the plugin, per OS (keys match Go's GOOS). The plugin supports exactly the OSes listed here.
   */
  entrypoint: {
    darwin?: PluginCommand;
    linux?: PluginCommand;
    windows?: PluginCommand;
  };
  /**
   * Actions the plugin exposes. Each becomes bindable as 'plugin.<id>.<action id>'.
   *
   * @minItems 1
   */
  actions: [PluginAction, ...PluginAction[]];
}
/**
 * Executable plus arguments used to start a plugin process.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "PluginCommand".
 */
export interface PluginCommand {
  /**
   * Executable to run. A path containing '/' is resolved relative to the plugin root; a bare name (e.g. 'node') is looked up on the PATH. Always use '/' as separator, also on Windows; absolute paths, '\' and ':' are not allowed.
   */
  path: string;
  /**
   * Arguments passed to the executable.
   */
  args?: string[];
}
/**
 * An action a plugin exposes, declared in its manifest.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "PluginAction".
 */
export interface PluginAction {
  /**
   * Action identifier, unique within the plugin. snake_case, no dots.
   */
  id: string;
  /**
   * Human-friendly action name for the UI.
   */
  name: string;
  /**
   * Optional longer description of what the action does.
   */
  description?: string;
  /**
   * Input kinds the action can be bound to. Omitted means any kind.
   *
   * @minItems 1
   */
  inputs?: [InputKind, ...InputKind[]];
  /**
   * Params this action accepts, in display order.
   */
  params: ParamSpec[];
}
