/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "DeviceID".
 */
export type DeviceID = string;
/**
 * Kind of physical input.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "InputKind".
 */
export type InputKind = "key" | "encoder";
/**
 * What happened on the input.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "InputAction".
 */
export type InputAction = "press" | "release" | "rotate_cw" | "rotate_ccw" | "click";

/**
 * Shared type definitions referenced by message schemas.
 */
export interface CommonTypes {
  [k: string]: unknown;
}
/**
 * A single hardware event coming from a HID device.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "InputEvent".
 */
export interface InputEvent {
  device_id: DeviceID;
  kind: InputKind;
  /**
   * Logical identifier of the input within the device (e.g. 'key_0x04', 'encoder_0'). Matches Device.inputs[].id.
   */
  input_id: string;
  action: InputAction;
  /**
   * Unix epoch in milliseconds when the event was captured by the daemon.
   */
  timestamp_ms: number;
}
/**
 * An executable action bound to an input.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Action".
 */
export interface Action {
  /**
   * Action type. Built-ins are well-known; plugin actions use 'plugin.<plugin_id>.<action_id>'.
   */
  type: string;
  /**
   * Action-specific parameters. Schema depends on 'type'. The daemon validates them against the per-type ActionParams definition (e.g. DelayActionParams for type 'delay').
   */
  params?: {
    [k: string]: unknown;
  };
}
/**
 * Params for the built-in 'send_keys' action: types a key combination.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "SendKeysActionParams".
 */
export interface SendKeysActionParams {
  /**
   * Key combination to send, e.g. 'Ctrl+Shift+S'.
   */
  keys: string;
}
/**
 * Params for the built-in 'launch_app' action: launches an application.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "LaunchAppActionParams".
 */
export interface LaunchAppActionParams {
  /**
   * Absolute path to the application or executable to launch.
   */
  path: string;
}
/**
 * Params for the built-in 'delay' action: waits for the given duration. Mainly useful as a step inside a macro.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "DelayActionParams".
 */
export interface DelayActionParams {
  /**
   * Milliseconds to wait before continuing.
   */
  ms: number;
}
/**
 * Params for the built-in 'macro' action: runs a sequence of actions in order. The schema allows any Action as a step; the daemon rejects nested macros (a step whose type is 'macro').
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "MacroActionParams".
 */
export interface MacroActionParams {
  /**
   * Actions to run in order. Must contain at least one step.
   *
   * @minItems 1
   */
  steps: [Action, ...Action[]];
}
/**
 * Maps an input on a specific device to an action.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Binding".
 */
export interface Binding {
  device_id: DeviceID;
  input_id: string;
  trigger: InputAction;
  action: Action;
}
/**
 * A named set of bindings. The daemon keeps exactly one profile active at a time; switching profiles swaps the active binding set.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Profile".
 */
export interface Profile {
  /**
   * Stable server-generated identifier for the profile.
   */
  id: string;
  /**
   * Human-friendly profile name.
   */
  name: string;
  /**
   * Bindings that belong to this profile.
   */
  bindings: Binding[];
}
/**
 * A single physical input exposed by a device (a key or an encoder).
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Input".
 */
export interface Input {
  /**
   * Logical identifier of the input within the device (e.g. 'key_0x04', 'encoder_0'). Matches InputEvent.input_id and Binding.input_id.
   */
  id: string;
  kind: InputKind;
  /**
   * Human-friendly label for the input (e.g. 'Key 1', 'Encoder'). Optional; clients fall back to id.
   */
  label?: string;
}
/**
 * A HID device known to the daemon. Returned by list_devices.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Device".
 */
export interface Device {
  id: DeviceID;
  /**
   * USB Vendor ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
   */
  vendor_id: string;
  /**
   * USB Product ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
   */
  product_id: string;
  /**
   * Manufacturer string from the HID descriptor. May be missing on cheap/clone devices.
   */
  manufacturer?: string;
  /**
   * Product name string from the HID descriptor.
   */
  product?: string;
  /**
   * Serial number string from the HID descriptor. Not all HID devices expose one.
   */
  serial_number?: string;
  /**
   * OS-opaque path used by the HID library to (re)open the device. Format varies per OS; clients should treat it as an opaque token.
   */
  path: string;
  /**
   * Inputs (keys/encoders) the daemon knows this device exposes. Empty for unrecognized devices the daemon can't map.
   */
  inputs: Input[];
}
/**
 * Maps a foreground application to the profile that should become active while that app is frontmost. When the frontmost app matches no rule, the active profile is left unchanged (sticky behavior); there is no fallback profile.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "AutoSwitchRule".
 */
export interface AutoSwitchRule {
  /**
   * OS-native application identifier: bundle id on macOS, executable name on Linux/Windows. Opaque string, not portable across OSes; the daemon matches it verbatim against the frontmost app.
   */
  app: string;
  /**
   * Identifier of the profile to activate when this app is frontmost.
   */
  profile_id: string;
}
