/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Stable identifier for a HID device. Format: VID_<hex>_PID_<hex>[_<serial>].
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "DeviceID".
 */
export type DeviceID = string;
/**
 * Kind of physical input.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "InputKind".
 */
export type InputKind = "key" | "encoder";
/**
 * What happened on the input.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "InputAction".
 */
export type InputAction = "press" | "release" | "rotate_cw" | "rotate_ccw" | "click";

/**
 * Shared type definitions referenced by message schemas.
 */
export interface CommonTypes {
  [k: string]: unknown;
}
/**
 * A single hardware event coming from a HID device.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "InputEvent".
 */
export interface InputEvent {
  device_id: DeviceID;
  kind: InputKind;
  /**
   * Logical identifier of the input within the device (e.g. 'K1', 'ENC1').
   */
  input_id: string;
  action: InputAction;
  /**
   * Unix epoch in milliseconds when the event was captured by the daemon.
   */
  timestamp_ms: number;
}
/**
 * An executable action bound to an input.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Action".
 */
export interface Action {
  /**
   * Action type. Built-ins are well-known; plugin actions use 'plugin.<plugin_id>.<action_id>'.
   */
  type: string;
  /**
   * Action-specific parameters. Schema depends on 'type'.
   */
  params?: {
    [k: string]: unknown;
  };
}
/**
 * Maps an input on a specific device to an action.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Binding".
 */
export interface Binding {
  device_id: DeviceID;
  input_id: string;
  trigger: InputAction;
  action: Action;
}
/**
 * A HID device known to the daemon. Returned by list_devices.
 *
 * This interface was referenced by `CommonTypes`'s JSON-Schema
 * via the `definition` "Device".
 */
export interface Device {
  id: DeviceID;
  /**
   * USB Vendor ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
   */
  vendor_id: string;
  /**
   * USB Product ID as a 4-digit hexadecimal string (lowercase or uppercase, no '0x' prefix).
   */
  product_id: string;
  /**
   * Manufacturer string from the HID descriptor. May be missing on cheap/clone devices.
   */
  manufacturer?: string;
  /**
   * Product name string from the HID descriptor.
   */
  product?: string;
  /**
   * Serial number string from the HID descriptor. Not all HID devices expose one.
   */
  serial_number?: string;
  /**
   * OS-opaque path used by the HID library to (re)open the device. Format varies per OS; clients should treat it as an opaque token.
   */
  path: string;
}
