/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Wire-level frame exchanged over the WebSocket transport. Every frame is one of three shapes discriminated by the 'type' field. Inner 'params'/'data'/'error' are intentionally generic here; method- and event-specific schemas refine them in a second validation pass.
 */
export type Envelope = Request | Response | Event;
/**
 * Server -> client. Discriminated by 'ok'.
 */
export type Response = ResponseOk | ResponseErr;

/**
 * Client -> server. Expects a correlated Response with the same id.
 */
export interface Request {
  type: "request";
  /**
   * Client-generated correlation id (UUID v4 or nanoid).
   */
  id: string;
  /**
   * Method name in snake_case.
   */
  method: string;
  /**
   * Method-specific arguments. Refined by the schema in schemas/methods/<method>.schema.json.
   */
  params: {
    [k: string]: unknown;
  };
}
export interface ResponseOk {
  type: "response";
  /**
   * Echo of the original Request.id.
   */
  id: string;
  ok: true;
  /**
   * Method-specific result. Refined by the schema in schemas/methods/<method>.schema.json.
   */
  data: {
    [k: string]: unknown;
  };
}
export interface ResponseErr {
  type: "response";
  /**
   * Echo of the original Request.id.
   */
  id: string;
  ok: false;
  error: Error;
}
/**
 * Failure payload returned in a Response with ok=false.
 */
export interface Error {
  /**
   * Stable, machine-readable error code in SCREAMING_SNAKE_CASE.
   */
  code: string;
  /**
   * Human-readable error message. Free form, may be localized in future versions.
   */
  message: string;
  /**
   * Optional structured context for debugging.
   */
  details?: {
    [k: string]: unknown;
  };
}
/**
 * Server -> client, no correlation. Stream of hardware events or daemon notifications.
 */
export interface Event {
  type: "event";
  /**
   * Event name in snake_case.
   */
  name: string;
  /**
   * Event-specific payload. Refined by the schema in schemas/events/<name>.schema.json.
   */
  data: {
    [k: string]: unknown;
  };
}
