# generated by datamodel-codegen:
#   filename:  methods/create_profile.schema.json

from typing import TypedDict

from .. import common_schema


class Params(TypedDict, closed=True):
    name: str
    """
    Human-friendly name for the new profile.
    """


class Result(TypedDict, closed=True):
    profile: common_schema.Profile


class MethodCreateProfile(TypedDict, closed=True):
    """
    Creates a new profile. The server generates the id and returns the profile with an empty bindings array.
    """

    params: Params
    result: Result
