# generated by datamodel-codegen:
#   filename:  methods/delete_profile.schema.json

from typing import TypedDict


class Params(TypedDict, closed=True):
    id: str
    """
    Identifier of the profile to delete.
    """


class Result(TypedDict, closed=True):
    active_profile_id: str
    """
    Identifier of the profile that is active after the deletion. Unchanged unless the deleted profile was the active one.
    """


class MethodDeleteProfile(TypedDict, closed=True):
    """
    Deletes a profile. The daemon never deletes the last remaining profile. Deleting the active profile reassigns the active one, so the resulting active profile id is always returned. Auto-switch rules whose profile_id points to the deleted profile are deleted with it, so the stored rule set never references a missing profile.
    """

    params: Params
    result: Result
