# generated by datamodel-codegen:
#   filename:  methods/duplicate_profile.schema.json

from typing import TypedDict

from .. import common_schema


class Params(TypedDict, closed=True):
    id: str
    """
    Identifier of the source profile to copy bindings from.
    """
    name: str
    """
    Human-friendly name for the new (duplicated) profile.
    """


class Result(TypedDict, closed=True):
    profile: common_schema.Profile


class MethodDuplicateProfile(TypedDict, closed=True):
    """
    Creates a copy of an existing profile under a new name. The server generates a new id and copies the source profile's bindings. Does not change the active profile.
    """

    params: Params
    result: Result
