# generated by datamodel-codegen:
#   filename:  methods/export_profile.schema.json

from typing import TypedDict


class Params(TypedDict, closed=True):
    id: str
    """
    Identifier of the profile to export.
    """
    path: str
    """
    Filesystem path on the daemon host where the exported file is written.
    """


class Result(TypedDict, closed=True):
    path: str
    """
    Echo of the path that was written.
    """


class MethodExportProfile(TypedDict, closed=True):
    """
    Serializes the profile identified by 'id' as a portable ExportedProfile document and writes it to 'path' on the daemon host's filesystem. The exported file omits the server-local id. Returns the path that was written.
    """

    params: Params
    result: Result
