# generated by datamodel-codegen:
#   filename:  methods/get_auto_switch.schema.json

from typing import TypedDict

from .. import common_schema
from .._json import JsonObject


class Result(TypedDict, closed=True):
    enabled: bool
    """
    Master toggle. When false, the daemon ignores the rules and never auto-switches.
    """
    rules: list[common_schema.AutoSwitchRule]
    """
    App-to-profile rules currently configured.
    """


class MethodGetAutoSwitch(TypedDict, closed=True):
    """
    Returns the current auto-switch configuration: the master toggle and the full set of app-to-profile rules. The daemon uses these to switch the active profile based on the foreground application.
    """

    params: JsonObject
    """
    No parameters in v1.
    """
    result: Result
