# generated by datamodel-codegen:
#   filename:  methods/hello.schema.json

from typing import Literal, TypedDict


class PeerInfo(TypedDict, closed=True):
    """
    Self-identification of a protocol peer (client or server).
    """

    name: str
    """
    Stable identifier of the peer implementation. A plugin must send its PluginID here; the daemon checks it against the plugin its auth token belongs to.
    """
    version: str
    """
    Semver version of the peer build.
    """


class Params(TypedDict, closed=True):
    protocol_version: Literal['1']
    """
    Major version of the protocol the client implements. Currently '1'.
    """
    client: PeerInfo


class Result(TypedDict, closed=True):
    protocol_version: Literal['1']
    """
    Protocol version the server agrees to speak for this session.
    """
    server: PeerInfo


class MethodHello(TypedDict, closed=True):
    """
    Mandatory first request after a WebSocket connection is established. The client declares the protocol_version it speaks. The server either accepts (Response.ok=true with its own identification) or closes the connection with an UNSUPPORTED_PROTOCOL_VERSION error. After a successful hello no further version negotiation happens; the contract is fixed for the session.
    """

    params: Params
    result: Result
