# generated by datamodel-codegen:
#   filename:  methods/import_profile.schema.json

from typing import TypedDict

from .. import common_schema


class Params(TypedDict, closed=True):
    path: str
    """
    Filesystem path on the daemon host of the exported file to import.
    """


class Result(TypedDict, closed=True):
    profile: common_schema.Profile


class MethodImportProfile(TypedDict, closed=True):
    """
    Reads an ExportedProfile document from 'path' on the daemon host's filesystem, validates it, and creates a new profile from it. The server generates a fresh id; any id in the file is ignored. Does not change the active profile. Returns the created profile.
    """

    params: Params
    result: Result
