# generated by datamodel-codegen:
#   filename:  methods/inspect_plugin.schema.json

from typing import NotRequired, TypedDict

from .. import common_schema


class Params(TypedDict, closed=True):
    path: str
    """
    Filesystem path on the daemon host of the '.keyforgeplugin' package.
    """


class Result(TypedDict, closed=True):
    manifest: common_schema.PluginManifest
    installed_version: NotRequired[str]
    """
    Version of the plugin with the same id that is currently installed, if any. Installing the package would replace it.
    """


class MethodInspectPlugin(TypedDict, closed=True):
    """
    Opens the '.keyforgeplugin' package at 'path' on the daemon host's filesystem and validates it exactly as install_plugin would (including rejecting a package with no entrypoint for the daemon host's OS), without installing or changing anything. Lets a client show a confirmation (name, author, version, actions) before installing.
    """

    params: Params
    result: Result
