# generated by datamodel-codegen:
#   filename:  methods/install_plugin.schema.json

from typing import NotRequired, TypedDict

from .. import common_schema


class Params(TypedDict, closed=True):
    path: str
    """
    Filesystem path on the daemon host of the '.keyforgeplugin' package.
    """


class Result(TypedDict, closed=True):
    plugin: common_schema.InstalledPlugin
    previous_version: NotRequired[str]
    """
    Version that was replaced, present only when the install was an upgrade.
    """


class MethodInstallPlugin(TypedDict, closed=True):
    """
    Installs the '.keyforgeplugin' package at 'path' on the daemon host's filesystem: validates it, extracts it into '<config dir>/plugins/<id>/' and starts the plugin. A package with no entrypoint for the daemon host's OS is rejected with an error and nothing is installed. The response is sent right after spawning, so the returned status is normally 'starting'; clients refresh with list_plugins. If a plugin with the same id is already installed, it is replaced (upgrade): the old process is stopped and its folder swapped atomically. Bindings are never modified, so existing bindings to the plugin's actions keep working after an upgrade.
    """

    params: Params
    result: Result
