# generated by datamodel-codegen:
#   filename:  methods/list_actions.schema.json

from typing import NotRequired, TypedDict

from .. import common_schema
from .._json import JsonObject


class ActionDescriptor(TypedDict, closed=True):
    """
    Describes a bindable action type and the params it accepts.
    """

    type: str
    """
    Action type, as used in Action.type (e.g. 'launch_app').
    """
    name: str
    """
    Human-friendly action name for the UI.
    """
    description: NotRequired[str]
    """
    Optional longer description of what the action does.
    """
    params: list[common_schema.ParamSpec]
    """
    Params this action accepts, in display order.
    """


class Result(TypedDict, closed=True):
    actions: list[ActionDescriptor]
    """
    All actions available to bind. Built-ins plus any registered plugin actions.
    """


class MethodListActions(TypedDict, closed=True):
    """
    Returns the catalog of actions the daemon can bind to inputs, including the param shape each action needs so a client can render a config form. No params in v1.
    """

    params: JsonObject
    """
    No parameters in v1.
    """
    result: Result
