# generated by datamodel-codegen:
#   filename:  methods/list_devices.schema.json

from typing import TypedDict

from .. import common_schema
from .._json import JsonObject


class Result(TypedDict, closed=True):
    devices: list[common_schema.Device]
    """
    All currently enumerated HID devices.
    """


class MethodListDevices(TypedDict, closed=True):
    """
    Returns the HID devices currently known to the daemon. No filters in v1; clients filter client-side if needed.
    """

    params: JsonObject
    """
    No parameters in v1.
    """
    result: Result
