# generated by datamodel-codegen:
#   filename:  methods/list_bindings.schema.json

from typing import TypedDict

from .. import common_schema
from .._json import JsonObject


class Result(TypedDict, closed=True):
    bindings: list[common_schema.Binding]
    """
    All currently configured bindings.
    """


class MethodListBindings(TypedDict, closed=True):
    """
    Returns all bindings the daemon currently has configured. Read-side counterpart of set_binding. No filters in v1; clients filter client-side if needed.
    """

    params: JsonObject
    """
    No parameters in v1.
    """
    result: Result
