# generated by datamodel-codegen:
#   filename:  methods/list_profiles.schema.json

from typing import TypedDict

from .. import common_schema
from .._json import JsonObject


class Result(TypedDict, closed=True):
    profiles: list[common_schema.Profile]
    """
    All profiles known to the daemon.
    """
    active_profile_id: str
    """
    Identifier of the currently active profile. Always references one of the profiles in the array.
    """


class MethodListProfiles(TypedDict, closed=True):
    """
    Returns all profiles the daemon currently has, along with the id of the active one. The active profile id is tracked at the daemon level and only exposed here.
    """

    params: JsonObject
    """
    No parameters in v1.
    """
    result: Result
