# generated by datamodel-codegen:
#   filename:  methods/list_plugins.schema.json

from typing import TypedDict

from .. import common_schema
from .._json import JsonObject


class Result(TypedDict, closed=True):
    plugins: list[common_schema.InstalledPlugin]
    """
    Installed plugins.
    """


class MethodListPlugins(TypedDict, closed=True):
    """
    Returns every installed plugin with the state of its process. No params in v1.
    """

    params: JsonObject
    """
    No parameters in v1.
    """
    result: Result
