# generated by datamodel-codegen:
#   filename:  methods/rename_profile.schema.json

from typing import TypedDict

from .._json import JsonObject


class Params(TypedDict, closed=True):
    id: str
    """
    Identifier of the profile to rename.
    """
    name: str
    """
    New human-friendly name for the profile.
    """


class MethodRenameProfile(TypedDict, closed=True):
    """
    Renames an existing profile. Does not affect its bindings or the active profile.
    """

    params: Params
    result: JsonObject
    """
    Empty acknowledgement object. Reserved for future fields without breaking the schema.
    """
