# generated by datamodel-codegen:
#   filename:  methods/set_binding.schema.json

from typing import TypedDict

from .. import common_schema
from .._json import JsonObject


class Params(TypedDict, closed=True):
    binding: common_schema.Binding


class MethodSetBinding(TypedDict, closed=True):
    """
    Creates or updates a binding (input -> action) on a device. The pair (device_id, input_id, trigger) is the unique key; calling this method with an existing key replaces the previous action.
    """

    params: Params
    result: JsonObject
    """
    Empty acknowledgement object. Reserved for future fields (e.g. server-assigned binding id) without breaking the schema.
    """
