# generated by datamodel-codegen:
#   filename:  methods/set_auto_switch.schema.json

from typing import TypedDict

from .. import common_schema


class Params(TypedDict, closed=True):
    enabled: bool
    """
    Master toggle. When false, the daemon ignores the rules and never auto-switches.
    """
    rules: list[common_schema.AutoSwitchRule]
    """
    Full replacement set of app-to-profile rules. Any previously stored rules are discarded.
    """


class Result(TypedDict, closed=True):
    enabled: bool
    """
    Master toggle as persisted. Echoes the requested value on success.
    """
    rules: list[common_schema.AutoSwitchRule]
    """
    Rules as persisted. Echoes the requested set on success.
    """


class MethodSetAutoSwitch(TypedDict, closed=True):
    """
    Replaces the entire auto-switch configuration in one shot (bulk set, not per-rule CRUD): the master toggle and the full rule set. The result echoes the persisted state. The daemon rejects the whole request with error code PROFILE_NOT_FOUND if any rule's profile_id does not exist; nothing is persisted in that case.
    """

    params: Params
    result: Result
