# generated by datamodel-codegen:
#   filename:  methods/set_input_color.schema.json

from typing import TypedDict

from .. import common_schema
from .._json import JsonObject


class Params(TypedDict, closed=True):
    device_id: common_schema.DeviceID
    input_id: str
    """
    Logical identifier of the input within the device. Matches Device.inputs[].id.
    """
    color: common_schema.Color


class MethodSetInputColor(TypedDict, closed=True):
    """
    Sets the LED color of an RGB-capable input in the active profile and paints it on the device. The pair (device_id, input_id) is the unique key; calling this method again replaces the previous color, and '#000000' turns the LED off. Colors belong to the profile: switching profiles repaints every RGB input with the new profile's colors. The daemon rejects inputs that are unknown or have no RGB LED (Input.rgb is not true).
    """

    params: Params
    result: JsonObject
    """
    Empty acknowledgement object.
    """
