# generated by datamodel-codegen:
#   filename:  methods/set_device_rotation.schema.json

from typing import TypedDict

from .. import common_schema
from .._json import JsonObject


class Params(TypedDict, closed=True):
    device_id: common_schema.DeviceID
    rotation: common_schema.DeviceRotation


class MethodSetDeviceRotation(TypedDict, closed=True):
    """
    Persists how the user has a device rotated on the desk, so clients draw its layout in that orientation. The rotation is stored per device (by device_id), not per profile: switching profiles does not change it. list_devices exposes it in Device.rotation. Presentation only: bindings and colors stay tied to input_id and are not touched. The daemon rejects unknown device_ids; error codes are defined by the daemon.
    """

    params: Params
    result: JsonObject
    """
    Empty acknowledgement object.
    """
