# generated by datamodel-codegen:
#   filename:  methods/set_active_profile.schema.json

from typing import TypedDict


class Params(TypedDict, closed=True):
    id: str
    """
    Identifier of the profile to activate.
    """


class Result(TypedDict, closed=True):
    active_profile_id: str
    """
    Identifier of the now-active profile. Echoes the requested id on success.
    """


class MethodSetActiveProfile(TypedDict, closed=True):
    """
    Sets which profile is active. The active profile is the one the binding editor reads and writes; switching it swaps the live binding set.
    """

    params: Params
    result: Result
