# generated by datamodel-codegen:
#   filename:  methods/uninstall_plugin.schema.json

from typing import TypedDict

from .. import common_schema
from .._json import JsonObject


class Params(TypedDict, closed=True):
    id: common_schema.PluginID
    """
    Id of the plugin to uninstall.
    """


class MethodUninstallPlugin(TypedDict, closed=True):
    """
    Stops the plugin's process and deletes its folder. Bindings that use the plugin's actions are left untouched (orphaned): while the plugin is missing, firing them does nothing, and reinstalling the plugin makes them work again.
    """

    params: Params
    result: JsonObject
    """
    Empty acknowledgement object. Reserved for future fields without breaking the schema.
    """
